import type { Metadata } from "next";
import { implementation } from "@/features/machine-reading/project";
export const metadata: Metadata = { title: "Public reading API", description: "Current public read-only API, eligibility and pagination.", alternates: { canonical: "/read-api" } };
export default function ReadApi() { return <main style={{maxWidth: "65ch", margin: "3rem auto", padding: "1rem"}}>
<h1>Public reading API</h1><p>{implementation[3].text}</p>
<p>This describes implemented routes in the release candidate, not a promise that remote production has been accepted. Reading these resources does not request suggestions or generate PNG files.</p>
<h2>Search</h2><p><code>GET /api/search/v1</code> accepts q, yearFrom, yearTo, objectType, theme, movement, first and after. first is 1–50; after is an opaque cursor returned by the response. Keep the query and filters unchanged when following a cursor. Exact public identifiers can return record-only entries; normal search uses reader-facing objects. <code>GET /api/search/v1/facets</code> takes no parameters.</p>
<h2>Index and Object reading</h2><p><code>GET /api/index/v1</code> returns one compact reader-facing catalogue, with schema version, releaseId, count, publicCount, recordOnlyCount, dictionaries and rows. It is not paginated. <code>/surfaces/ID</code> provides the public HTML record; unknown or held IDs return 404. Source attributions and rights remain record-specific.</p>
<h2>Versions, errors and limits</h2><p>Search includes release and index identities in its response and Archive response headers. Invalid search input or cursor returns 400; unsupported methods return 405; oversized URLs return 414; unavailable Search returns 503. Do not retry invalid input. The public reading routes currently do not implement a per-requester quota; infrastructure limits may still apply. The separate 30-per-minute suggestions policy is not an archive API or daily spending limit. Use bounded requests and cache versioned results.</p>
<p><a href="/openapi.json">OpenAPI description</a> · <a href="/source">Source and rights</a> · <a href="/about#implementation">Project implementation</a></p></main>; }
