/* Exploration — the copy (FRONTEND_DESIGN_DECISION.md §7i). The owner's
   concept sentence is the statement; every other line restates what the
   governed view shows. No copy claims a relation's direction, cause,
   chronology, strength or importance. */

export const NAME = "Exploration";
export const KICKER = "TRACE · Research view";
export const STATEMENT =
  "Choose one starting point and MGDA draws a view from its validated associations. Make it simpler or richer, or ask for another view.";

export const STARTING_POINT = "Starting point";
export const CHANGE = "Change";
export const CHOOSE_TITLE = "Choose a starting point";
export const CHOOSE_NOTE = "Choose a new starting point.";
export const CHOOSER_CLOSE = "Keep current";
export const CURRENT = "Current";
export const CATEGORY_WORDS: Readonly<Record<string, string>> = Object.freeze({
  region: "Region",
  theme: "Theme",
  medium: "Medium / format",
  movement: "Movement context",
});

export const COMPLEXITY = "Complexity";
export const COMPLEXITY_NOTE = "";
export const LESS = "Less";
export const MORE = "More";
export const TERMS = (count: number): string => `${count} ${count === 1 ? "term" : "terms"}`;
export const AT_RICHEST = "Richest available view.";
export const AT_SIMPLEST = "Simplest available view.";
export const ONLY_SIZE = "The only available size.";

export const ANOTHER_VIEW = "Another view";
export const ANOTHER_VIEW_NOTE = (position: number, size: number): string => `View ${position} of ${size} for this starting point`;
export const SINGLE_VIEW = "A single view for this starting point";

export const EXPORT = "Export current view";
export const EXPORT_NOTE = (form: string, width: number, height: number): string => `${form} · PNG ${width} × ${height}`;
export const EXPORTING = "Exporting…";
export const EXPORT_FAILED = "The export could not be rendered. The view is unchanged.";

export const OPEN_INQUIRY = "Open inquiry";
export const OPEN_INQUIRY_COUNT = (count: number): string => `${count} unresolved ${count === 1 ? "question" : "questions"}`;
export const OPEN_INQUIRY_DISCLOSURE: readonly [string, string, string] = Object.freeze([
  "Open inquiry",
  "Evidence remains incomplete.",
  "This is not a validated historical association.",
]) as readonly [string, string, string];
export const INQUIRY_SCOPE = "Scope";
export const INQUIRY_FORM = "Relation form";
export const INQUIRY_EVIDENCE_GAP = "Evidence gap";
export const INQUIRY_SOURCE_BOUNDARY = "Source boundary";
export const INQUIRY_EVIDENCE_GAP_TEXT = "Current evidence is not sufficient to include this question in the validated graph.";
export const INQUIRY_SOURCE_BOUNDARY_TEXT = "This question remains separate from the validated exploration and does not change the current view. Source details are not public in this release.";
export const INQUIRY_CHOOSE = "Eleven open questions, kept apart from the view. Choose one to read it.";
export const INQUIRY_KIND = "Open inquiry";
export const INQUIRY_PROVENANCE = "Technical provenance";
export const INQUIRY_BACK = "All questions";

export const DESCRIPTION = "Description";
export const DESCRIPTION_CLOSE = "Close Description";
export const VISIBLE_TERMS = (count: number): string => `${count} ${count === 1 ? "term" : "terms"}`;
export const QUALIFIED_ASSOCIATIONS = (count: number): string => `${count} qualified generic ${count === 1 ? "association" : "associations"}`;
export const WHAT_IS_SHOWN = "What is shown";
export const PROVENANCE = "Technical provenance";
export const PRESENTATION = "Presentation";
/* the association details entry (release pass): what the release can publish about one drawn association */
export const ASSOCIATION_DETAILS = "View association details";
export const ASSOCIATION_ENDPOINTS = "Association";
export const ASSOCIATION_BASIS = "Basis / scope";
export const ASSOCIATION_SOURCES = "Sources";
export const ASSOCIATION_SOURCES_NOT_PUBLIC = "Source details are not public in this release.";
export const PRESENTATION_NOTE = "Layout and styling are presentational only.";
export const SUGGESTS = "System suggests";
/* the fixed boundary under the narration — the disclaimer lives here once, not in every sentence */
export const SUGGESTS_BOUNDARY = "Associations shown here are exploratory, not causal or directional. The view is generated from validated associations; its structure is system-defined.";

export const STAGE_LABEL = "Exploration view: a governed composition drawn as a stamp. The picture is generated by the system; it cannot be edited.";
export const STATUS = (start: string, terms: number, associations: number): string =>
  `${start} · ${TERMS(terms)} · ${associations} ${associations === 1 ? "association" : "associations"}`;
export const LOADING = "Building the view…";
export const STALE = "The view changed elsewhere. It has been refreshed.";
export const FAILED = "The governed view could not be built.";


/* the failure page */
export const FAILURE_KICKER = "TRACE · Exploration";
export const FAILURE_TITLE = "Exploration is unavailable";
export const FAILURE_NOTE = "The governed exploration projection failed its integrity checks. Nothing was mounted.";
export const FAILURE_BACK = "Return to TRACE";
