from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


classification_axes_fields = [
    "axis_id",
    "axis_name",
    "axis_type",
    "required_for_launch",
    "required_for_record",
    "supports_multiple",
    "api_filter",
    "controlled_source",
    "notes",
]

classification_axes = [
    {
        "axis_id": "AX001",
        "axis_name": "macro_region",
        "axis_type": "geography",
        "required_for_launch": "yes",
        "required_for_record": "yes",
        "supports_multiple": "yes",
        "api_filter": "yes",
        "controlled_source": "regions; geographies",
        "notes": "Top-level geographic frame. Must never be the only geographic value when a country, territory, or city is known.",
    },
    {
        "axis_id": "AX002",
        "axis_name": "country_or_context",
        "axis_type": "geography",
        "required_for_launch": "yes",
        "required_for_record": "when_known",
        "supports_multiple": "yes",
        "api_filter": "yes",
        "controlled_source": "geographies",
        "notes": "Supports countries, territories, historical jurisdictions, and context areas where modern borders are not sufficient.",
    },
    {
        "axis_id": "AX003",
        "axis_name": "city_or_place",
        "axis_type": "geography",
        "required_for_launch": "yes",
        "required_for_record": "when_known",
        "supports_multiple": "yes",
        "api_filter": "yes",
        "controlled_source": "geographies; source text",
        "notes": "Used for production, publication, circulation, institution location, and event location.",
    },
    {
        "axis_id": "AX004",
        "axis_name": "date_start/date_end/date_text",
        "axis_type": "date",
        "required_for_launch": "yes",
        "required_for_record": "yes",
        "supports_multiple": "no",
        "api_filter": "yes",
        "controlled_source": "source text; normalized date rules",
        "notes": "Every record must preserve source date text and normalized start/end where possible.",
    },
    {
        "axis_id": "AX005",
        "axis_name": "date_basis",
        "axis_type": "date",
        "required_for_launch": "yes",
        "required_for_record": "yes",
        "supports_multiple": "yes",
        "api_filter": "yes",
        "controlled_source": "object_date; publication_date; event_date; capture_date; digitization_date",
        "notes": "Prevents object date, publication date, and archive capture date from being collapsed.",
    },
    {
        "axis_id": "AX006",
        "axis_name": "historical_node",
        "axis_type": "history",
        "required_for_launch": "yes",
        "required_for_record": "yes",
        "supports_multiple": "yes",
        "api_filter": "yes",
        "controlled_source": "historical_nodes",
        "notes": "Records may be node_pending during review, but publication should expose the pending state.",
    },
    {
        "axis_id": "AX007",
        "axis_name": "movement_or_formation",
        "axis_type": "history",
        "required_for_launch": "yes",
        "required_for_record": "when_supported",
        "supports_multiple": "yes",
        "api_filter": "yes",
        "controlled_source": "movements; regional_movements",
        "notes": "Includes movements, schools, publishing cultures, state formations, technical regimes, and counterpublic formations.",
    },
    {
        "axis_id": "AX008",
        "axis_name": "medium_technology_format",
        "axis_type": "media",
        "required_for_launch": "yes",
        "required_for_record": "yes",
        "supports_multiple": "yes",
        "api_filter": "yes",
        "controlled_source": "media_technologies",
        "notes": "Separates object type, production technology, circulation format, and preservation/capture format when possible.",
    },
    {
        "axis_id": "AX009",
        "axis_name": "language_script",
        "axis_type": "language",
        "required_for_launch": "yes",
        "required_for_record": "when_known",
        "supports_multiple": "yes",
        "api_filter": "yes",
        "controlled_source": "source text; language/script fields",
        "notes": "Required for CJK, Hangul, Arabic, Hebrew, Devanagari, Bengali, Latin, Cyrillic, and multilingual records.",
    },
    {
        "axis_id": "AX010",
        "axis_name": "source_rights_provenance",
        "axis_type": "source",
        "required_for_launch": "yes",
        "required_for_record": "yes",
        "supports_multiple": "yes",
        "api_filter": "yes",
        "controlled_source": "sources; citations; rights_reviews",
        "notes": "Every publishable record needs source URL, access date, citation, rights state, and display policy.",
    },
]


geographies_fields = [
    "geo_id",
    "name",
    "parent_geo_id",
    "region_id",
    "geo_type",
    "iso_code",
    "language_scope",
    "script_scope",
    "date_scope",
    "notes",
]

geo_seed = [
    ("GEO001", "Global / transnational", "", "", "transnational_context", "", "multiple", "multiple", "all periods", "Use for cross-border circulation; must be paired with specific geographies when known."),
    ("GEO002", "Western and Central Europe", "", "REG001", "macro_region", "", "multiple European languages", "Latin", "modern", "Parent context for Western/Central European records."),
    ("GEO003", "United Kingdom", "GEO002", "REG001", "country_context", "GB", "English; Welsh; Scots Gaelic; others", "Latin", "modern", "Includes British print, advertising, publishing, punk, and design education contexts."),
    ("GEO004", "Ireland", "GEO002", "REG001", "country_context", "IE", "English; Irish", "Latin", "modern", "Track separately from UK contexts."),
    ("GEO005", "France", "GEO002", "REG001", "country_context", "FR", "French", "Latin", "modern", "Important for poster, magazine, avant-garde, state and commercial graphics."),
    ("GEO006", "Germany", "GEO002", "REG001", "country_context", "DE", "German", "Latin", "modern", "Includes reform, Bauhaus, New Typography, Ulm, corporate systems, and publishing."),
    ("GEO007", "Switzerland", "GEO002", "REG001", "country_context", "CH", "German; French; Italian; Romansh", "Latin", "modern", "Important for International Typographic Style and information systems."),
    ("GEO008", "Austria", "GEO002", "REG001", "country_context", "AT", "German", "Latin", "modern", "Includes Vienna Secession and modern publishing contexts."),
    ("GEO009", "Netherlands", "GEO002", "REG001", "country_context", "NL", "Dutch", "Latin", "modern", "Includes De Stijl, modern publishing, and public information design."),
    ("GEO010", "Belgium", "GEO002", "REG001", "country_context", "BE", "Dutch; French; German", "Latin", "modern", "Important for Art Nouveau and poster/print cultures."),
    ("GEO011", "Italy", "GEO002", "REG001", "country_context", "IT", "Italian", "Latin", "modern", "Includes Futurism, Milan systems, publishing, and corporate design."),
    ("GEO012", "Spain", "GEO002", "REG001", "country_context", "ES", "Spanish; Catalan; Basque; Galician", "Latin", "modern", "Includes Catalan modernisme, civil-war graphics, posters, and publishing."),
    ("GEO013", "Portugal", "GEO002", "REG001", "country_context", "PT", "Portuguese", "Latin", "modern", "Includes print, political graphics, publishing, and colonial/postcolonial links."),
    ("GEO014", "Nordic countries", "GEO002", "REG001", "regional_context", "", "Danish; Swedish; Norwegian; Finnish; Icelandic; Sami languages", "Latin", "modern", "Use with country-specific rows where known."),
    ("GEO015", "Eastern Europe, Balkans, and socialist contexts", "", "REG002", "macro_region", "", "multiple", "Latin; Cyrillic", "modern", "Parent context for Central/Eastern Europe and socialist/non-aligned design histories."),
    ("GEO016", "Russia / USSR contexts", "GEO015", "REG002", "historical_context", "RU", "Russian; Soviet republic languages", "Cyrillic; Latin; others", "1917-1991; modern", "Use carefully to distinguish Russian, Soviet, and republic-specific contexts."),
    ("GEO017", "Ukraine", "GEO015", "REG002", "country_context", "UA", "Ukrainian; Russian; others", "Cyrillic; Latin", "modern", "Do not collapse into USSR/Russia."),
    ("GEO018", "Poland", "GEO015", "REG002", "country_context", "PL", "Polish", "Latin", "modern", "Important for poster school, publishing, and post-socialist design."),
    ("GEO019", "Czech and Slovak contexts", "GEO015", "REG002", "regional_context", "", "Czech; Slovak", "Latin", "modern", "Includes Czechoslovak design, typography, posters, and publishing."),
    ("GEO020", "Hungary", "GEO015", "REG002", "country_context", "HU", "Hungarian", "Latin", "modern", "Includes avant-garde, poster, and socialist-era graphic design."),
    ("GEO021", "Romania", "GEO015", "REG002", "country_context", "RO", "Romanian", "Latin", "modern", "Important for poster, publishing, and state design contexts."),
    ("GEO022", "Bulgaria", "GEO015", "REG002", "country_context", "BG", "Bulgarian", "Cyrillic", "modern", "Important for socialist graphics and posters."),
    ("GEO023", "Former Yugoslav contexts", "GEO015", "REG002", "historical_context", "", "Serbo-Croatian; Slovenian; Macedonian; others", "Latin; Cyrillic", "modern", "Includes non-aligned socialist design, tourism graphics, and poster cultures."),
    ("GEO024", "North America", "", "REG003", "macro_region", "", "English; French; Spanish; Indigenous languages", "Latin; Indigenous scripts", "modern", "Parent context for U.S., Canada, Mexico, and Indigenous/transborder histories."),
    ("GEO025", "United States", "GEO024", "REG003", "country_context", "US", "English; Spanish; Indigenous languages; others", "Latin; Indigenous scripts", "modern", "Advertising, corporate identity, editorial, protest, digital, and community archives."),
    ("GEO026", "Canada", "GEO024", "REG003", "country_context", "CA", "English; French; Indigenous languages", "Latin; Indigenous scripts", "modern", "Track separately from U.S. design history."),
    ("GEO027", "Mexico", "GEO024", "REG004", "country_context", "MX", "Spanish; Indigenous languages", "Latin; Indigenous scripts", "modern", "Bridge North American and Latin American histories; posters, print, publishing, Olympics identity."),
    ("GEO028", "Latin America and the Caribbean", "", "REG004", "macro_region", "", "Spanish; Portuguese; French; English; Indigenous languages; creoles", "Latin; Indigenous scripts", "modern", "Parent context; must be decomposed by country/region when possible."),
    ("GEO029", "Cuba", "GEO028", "REG004", "country_context", "CU", "Spanish", "Latin", "modern", "Political posters, film posters, solidarity graphics, publishing."),
    ("GEO030", "Brazil", "GEO028", "REG004", "country_context", "BR", "Portuguese; Indigenous languages", "Latin; Indigenous scripts", "modern", "Modernism, concrete art/design, typography, editorial, identity, digital culture."),
    ("GEO031", "Argentina", "GEO028", "REG004", "country_context", "AR", "Spanish", "Latin", "modern", "Publishing, posters, modernism, political graphics, design education."),
    ("GEO032", "Chile", "GEO028", "REG004", "country_context", "CL", "Spanish; Indigenous languages", "Latin; Indigenous scripts", "modern", "Political posters, publishing, socialist/solidarity graphics, contemporary design."),
    ("GEO033", "Colombia and Andean contexts", "GEO028", "REG004", "regional_context", "", "Spanish; Indigenous languages", "Latin; Indigenous scripts", "modern", "Use for Colombia, Peru, Ecuador, Bolivia, and related Andean source discovery."),
    ("GEO034", "Caribbean contexts", "GEO028", "REG004", "regional_context", "", "Spanish; English; French; Dutch; creoles", "Latin", "modern", "Supports island-specific and diaspora visual communication."),
    ("GEO035", "East Asia", "", "REG007", "macro_region", "", "Chinese; Japanese; Korean; others", "Han; Kana; Hangul; Latin", "modern", "Parent context only; avoid flattening."),
    ("GEO036", "Japan", "GEO035", "REG005", "country_context", "JP", "Japanese; English", "Kanji; Hiragana; Katakana; Latin", "modern", "Posters, magazines, typography, corporate identity, packaging, interface/game/platform cultures."),
    ("GEO037", "Korean Peninsula", "GEO035", "REG006", "regional_context", "", "Korean", "Hangul; Hanja; Latin", "modern", "Use when source scope predates or crosses North/South Korean division."),
    ("GEO038", "South Korea", "GEO037", "REG006", "country_context", "KR", "Korean; English", "Hangul; Hanja; Latin", "modern", "Hangul typography, print, corporate identity, political graphics, digital platforms."),
    ("GEO039", "North Korea", "GEO037", "REG006", "country_context", "KP", "Korean", "Hangul; Hanja", "modern", "State visual communication and posters; rights/source access constraints are high."),
    ("GEO040", "Mainland China", "GEO035", "REG008", "country_context", "CN", "Chinese; minority languages; English", "Simplified Chinese; Traditional Chinese historical; Latin; others", "modern", "Late Qing print, Republican Shanghai, socialist design, reform-era branding, platform culture."),
    ("GEO041", "Hong Kong", "GEO035", "REG009", "city/territory_context", "HK", "Chinese; Cantonese; English", "Traditional Chinese; Latin", "modern", "Bilingual typography, film/poster graphics, publishing, advertising, protest graphics."),
    ("GEO042", "Taiwan", "GEO035", "REG010", "country/territory_context", "TW", "Chinese; Taiwanese Hokkien; Japanese historical; English", "Traditional Chinese; Kana historical; Latin", "modern", "Japanese colonial, postwar, democratization, publishing, identity, digital culture."),
    ("GEO043", "Southeast Asia", "", "REG011", "macro_region", "", "multiple", "Latin; Thai; Khmer; Burmese; Han; Arabic-derived scripts", "modern", "Parent context; must be decomposed country by country."),
    ("GEO044", "Indonesia", "GEO043", "REG011", "country_context", "ID", "Indonesian; regional languages; Dutch historical", "Latin; Javanese; others", "modern", "Colonial print, independence graphics, advertising, contemporary digital."),
    ("GEO045", "Malaysia and Singapore", "GEO043", "REG011", "regional_context", "", "Malay; English; Chinese; Tamil", "Latin; Han; Tamil; Arabic-derived Jawi", "modern", "Multilingual typography, advertising, publishing, state campaigns."),
    ("GEO046", "Thailand", "GEO043", "REG011", "country_context", "TH", "Thai; English", "Thai; Latin", "modern", "Thai typography, advertising, posters, publishing, digital culture."),
    ("GEO047", "Vietnam", "GEO043", "REG011", "country_context", "VN", "Vietnamese; French; Chinese historical", "Latin; Han/Nom historical", "modern", "Colonial print, propaganda, publishing, poster culture."),
    ("GEO048", "Philippines", "GEO043", "REG011", "country_context", "PH", "Filipino; English; Spanish historical; regional languages", "Latin; Baybayin revival contexts", "modern", "Colonial print, advertising, political graphics, popular media."),
    ("GEO049", "Mainland Southeast Asia contexts", "GEO043", "REG011", "regional_context", "", "Khmer; Burmese; Lao; English; French", "Khmer; Burmese; Lao; Latin", "modern", "Cambodia, Myanmar, Laos; under-digitized sources need explicit tracking."),
    ("GEO050", "South Asia", "", "REG012", "macro_region", "", "multiple South Asian languages; English", "Devanagari; Bengali; Perso-Arabic; Tamil; Telugu; Malayalam; Sinhala; Latin; others", "modern", "Parent context for multilingual type and print histories."),
    ("GEO051", "India", "GEO050", "REG012", "country_context", "IN", "Hindi; Bengali; Tamil; Telugu; Malayalam; Marathi; English; others", "multiple Indic scripts; Latin", "modern", "Publishing, film graphics, political posters, state design, type design, digital."),
    ("GEO052", "Pakistan", "GEO050", "REG012", "country_context", "PK", "Urdu; English; Punjabi; Sindhi; Pashto; others", "Perso-Arabic; Latin", "modern", "Urdu typography, publishing, posters, state and commercial graphics."),
    ("GEO053", "Bangladesh", "GEO050", "REG012", "country_context", "BD", "Bengali; English", "Bengali; Latin", "modern", "Language movement visual culture, publishing, posters, typography."),
    ("GEO054", "Sri Lanka", "GEO050", "REG012", "country_context", "LK", "Sinhala; Tamil; English", "Sinhala; Tamil; Latin", "modern", "Multilingual state, publishing, poster, and commercial print contexts."),
    ("GEO055", "Middle East and North Africa", "", "REG013", "macro_region", "", "Arabic; Persian; Hebrew; Turkish; French; English; others", "Arabic; Hebrew; Latin", "modern", "Parent context; requires right-to-left support later."),
    ("GEO056", "Egypt", "GEO055", "REG013", "country_context", "EG", "Arabic; English; French historical", "Arabic; Latin", "modern", "Publishing, film posters, political graphics, Arabic typography."),
    ("GEO057", "Iran", "GEO055", "REG013", "country_context", "IR", "Persian; Azerbaijani; Kurdish; others", "Arabic-derived Persian; Latin", "modern", "Persian typography, revolutionary posters, publishing, contemporary design."),
    ("GEO058", "Turkey", "GEO055", "REG013", "country_context", "TR", "Turkish; Kurdish; others", "Latin; Arabic historical", "modern", "Script reform, publishing, state modernization, poster and identity design."),
    ("GEO059", "Levant contexts", "GEO055", "REG013", "regional_context", "", "Arabic; Hebrew; French; English; Armenian; others", "Arabic; Hebrew; Latin; Armenian", "modern", "Lebanon, Palestine, Israel, Syria, Jordan; political, publishing, and multilingual typography."),
    ("GEO060", "Maghreb contexts", "GEO055", "REG013", "regional_context", "", "Arabic; French; Tamazight; others", "Arabic; Latin; Tifinagh", "modern", "Morocco, Algeria, Tunisia; postcolonial print, posters, publishing."),
    ("GEO061", "Africa", "", "REG014", "macro_region", "", "multiple", "Latin; Arabic; Ethiopic; others", "modern", "Parent context; avoid continent-only categorization."),
    ("GEO062", "South Africa", "GEO061", "REG014", "country_context", "ZA", "English; Afrikaans; Zulu; Xhosa; others", "Latin; others", "modern", "Anti-apartheid graphics, publishing, advertising, contemporary design."),
    ("GEO063", "Nigeria", "GEO061", "REG014", "country_context", "NG", "English; Yoruba; Hausa; Igbo; others", "Latin; Arabic-derived Ajami; others", "modern", "Publishing, advertising, film/Nollywood graphics, digital culture."),
    ("GEO064", "Ghana", "GEO061", "REG014", "country_context", "GH", "English; Akan; Ewe; others", "Latin; others", "modern", "Independence-era graphics, publishing, sign painting, contemporary design."),
    ("GEO065", "Kenya and East African contexts", "GEO061", "REG014", "regional_context", "", "English; Swahili; Amharic; Somali; others", "Latin; Ethiopic; Arabic", "modern", "Publishing, political graphics, advertising, digital visual culture."),
    ("GEO066", "West African francophone contexts", "GEO061", "REG014", "regional_context", "", "French; Wolof; Bambara; Arabic; others", "Latin; Arabic", "modern", "Senegal, Mali, Cote d'Ivoire and related print/poster/design histories."),
    ("GEO067", "North African contexts", "GEO061", "REG014", "regional_context", "", "Arabic; French; Tamazight; others", "Arabic; Latin; Tifinagh", "modern", "Also cross-links MENA; use for African coverage matrix."),
    ("GEO068", "Oceania and Pacific", "", "REG015", "macro_region", "", "English; Maori; Indigenous Australian languages; Pacific languages", "Latin; local orthographies", "modern", "Parent context for Australia, Aotearoa New Zealand, and Pacific islands."),
    ("GEO069", "Australia", "GEO068", "REG015", "country_context", "AU", "English; Indigenous Australian languages", "Latin; local orthographies", "modern", "Public information, publishing, Indigenous/community protocols, web archives."),
    ("GEO070", "Aotearoa New Zealand", "GEO068", "REG015", "country_context", "NZ", "English; Maori", "Latin; Maori orthography", "modern", "Bicultural design, public information, publishing, identity systems."),
    ("GEO071", "Pacific Islands contexts", "GEO068", "REG015", "regional_context", "", "Pacific languages; English; French", "Latin; local orthographies", "modern", "Community protocols and under-digitized source gaps are central."),
]

geographies = [
    {
        "geo_id": row[0],
        "name": row[1],
        "parent_geo_id": row[2],
        "region_id": row[3],
        "geo_type": row[4],
        "iso_code": row[5],
        "language_scope": row[6],
        "script_scope": row[7],
        "date_scope": row[8],
        "notes": row[9],
    }
    for row in geo_seed
]

geography_audit_seed = [
    ("GEO072", "Central Asia", "GEO015", "REG002", "regional_context", "", "Kazakh; Uzbek; Kyrgyz; Tajik; Turkmen; Russian; others", "Latin; Cyrillic; Arabic-derived historical", "modern", "Added from Global Coverage Audit; separates Soviet/post-Soviet script and print histories from Russia-centered contexts."),
    ("GEO073", "Kazakhstan", "GEO072", "REG002", "country_context", "KZ", "Kazakh; Russian", "Cyrillic; Latin; Arabic historical", "modern", "Modern print, public graphics, Soviet/post-Soviet script transition."),
    ("GEO074", "Uzbekistan", "GEO072", "REG002", "country_context", "UZ", "Uzbek; Russian; Tajik", "Latin; Cyrillic; Arabic historical", "modern", "Script reforms and multilingual print contexts."),
    ("GEO075", "Kyrgyzstan", "GEO072", "REG002", "country_context", "KG", "Kyrgyz; Russian", "Cyrillic; Latin", "modern", "Public graphics and Soviet/post-Soviet print."),
    ("GEO076", "Tajikistan", "GEO072", "REG002", "country_context", "TJ", "Tajik; Russian", "Cyrillic; Persian/Arabic historical", "modern", "Persian/Cyrillic transition and state print."),
    ("GEO077", "Turkmenistan", "GEO072", "REG002", "country_context", "TM", "Turkmen; Russian", "Latin; Cyrillic; Arabic historical", "modern", "State print and script transition."),
    ("GEO078", "Caucasus", "GEO015", "REG002", "regional_context", "", "Armenian; Georgian; Azerbaijani; Russian; others", "Armenian; Georgian; Latin; Cyrillic; Arabic-derived", "modern", "Added from Global Coverage Audit; distinct scripts, Soviet/post-Soviet histories, and diaspora routes."),
    ("GEO079", "Armenia", "GEO078", "REG002", "country_context", "AM", "Armenian; Russian", "Armenian; Cyrillic", "modern", "Print, poster, book culture, and diaspora design routes."),
    ("GEO080", "Georgia", "GEO078", "REG002", "country_context", "GE", "Georgian; Russian", "Georgian; Cyrillic", "modern", "Periodical and book culture with distinct script support."),
    ("GEO081", "Azerbaijan", "GEO078", "REG002", "country_context", "AZ", "Azerbaijani; Russian; Persian historical", "Latin; Cyrillic; Arabic-derived", "modern", "Periodical, music print, and script-transition context."),
    ("GEO082", "Caucasus diaspora routes", "GEO078", "REG002", "diaspora_context", "", "multiple", "multiple", "modern", "Diasporic print and cultural circulation route."),
    ("GEO083", "Iran", "GEO055", "REG013", "country_context", "IR", "Persian; Azerbaijani; Kurdish; Arabic; others", "Arabic-derived Persian; Latin", "modern", "First-class Persian print, public graphics, revolutionary poster, and diaspora design context."),
    ("GEO084", "Mandatory Palestine", "GEO059", "REG013", "historical_context", "", "Arabic; Hebrew; English; Yiddish; Ladino", "Arabic; Hebrew; Latin", "1917-1948", "Historical print and newspaper context; do not collapse into present-day borders."),
    ("GEO085", "Palestinian territories and diaspora", "GEO059", "REG013", "country/territory_context", "PS", "Arabic; English; others", "Arabic; Latin", "modern", "Poster, periodical, solidarity, and diaspora print networks."),
    ("GEO086", "Israel Hebrew/Arabic press contexts", "GEO059", "REG013", "country_context", "IL", "Hebrew; Arabic; English; Russian; others", "Hebrew; Arabic; Latin; Cyrillic", "modern", "Hebrew/Arabic press, publishing, and public graphics; rights/geopolitical sensitivity high."),
    ("GEO087", "Jamaica", "GEO034", "REG004", "country_context", "JM", "English; Jamaican Patois", "Latin", "modern", "Music, broadcast, tourism, political, and newspaper graphics."),
    ("GEO088", "Trinidad and Tobago", "GEO034", "REG004", "country_context", "TT", "English; Trinidadian/Tobagonian Creole; others", "Latin", "modern", "Carnival, music, tourism, and commercial graphics."),
    ("GEO089", "Haiti", "GEO034", "REG004", "country_context", "HT", "Haitian Creole; French", "Latin", "modern", "Political print, newspapers, diasporic and cultural graphics."),
    ("GEO090", "Dominican Republic", "GEO034", "REG004", "country_context", "DO", "Spanish", "Latin", "modern", "Print, tourism, music, political and commercial graphics."),
    ("GEO091", "Caribbean diaspora routes", "GEO034", "REG004", "diaspora_context", "", "English; Spanish; French; Dutch; creoles; others", "Latin", "modern", "Routes through migration, music, carnival, publishing, and political circulation."),
    ("GEO092", "Nepal", "GEO050", "REG012", "country_context", "NP", "Nepali; Newar; Maithili; English; others", "Devanagari; Ranjana historical; Latin", "modern", "Nepali periodical and public graphics; prevents South Asia from becoming India-only."),
    ("GEO093", "Cambodia", "GEO043", "REG011", "country_context", "KH", "Khmer; French; English", "Khmer; Latin", "modern", "Khmer print, state graphics, periodicals, and post-conflict archives."),
    ("GEO094", "Myanmar", "GEO043", "REG011", "country_context", "MM", "Burmese; minority languages; English", "Burmese; Latin", "modern", "Burmese periodical and public graphics."),
    ("GEO095", "Singapore", "GEO045", "REG011", "country_context", "SG", "English; Malay; Chinese; Tamil", "Latin; Han; Tamil; Jawi historical", "modern", "Multilingual state campaigns, posters, newspapers, and web archives."),
    ("GEO096", "Singapore/Malaya Jawi-Rumi contexts", "GEO045", "REG011", "historical_context", "", "Malay; English; Chinese; Tamil", "Jawi; Latin; Han; Tamil", "modern", "Script transition, Malay print, and state/commercial multilingual design."),
    ("GEO097", "West Africa", "GEO061", "REG014", "regional_context", "", "English; French; Portuguese; Arabic; African languages", "Latin; Arabic; others", "modern", "Independence graphics, newspapers, signs, posters, commercial vernaculars."),
    ("GEO098", "Horn of Africa", "GEO061", "REG014", "regional_context", "", "Amharic; Tigrinya; Somali; Arabic; English; others", "Ethiopic; Latin; Arabic", "modern", "Ge'ez/Amharic/Arabic/Latin script intersections."),
    ("GEO099", "Ethiopia", "GEO098", "REG014", "country_context", "ET", "Amharic; Oromo; Tigrinya; Somali; English; others", "Ethiopic; Latin; Arabic", "modern", "Ethiopic script, public print, posters, and periodical culture."),
    ("GEO100", "Senegal", "GEO066", "REG014", "country_context", "SN", "French; Wolof; Arabic; others", "Latin; Arabic", "modern", "Francophone West African design, print, and political/cultural graphics."),
    ("GEO101", "Namibia", "GEO061", "REG014", "country_context", "NA", "English; Afrikaans; German; Indigenous languages", "Latin", "modern", "Liberation graphics and southern African solidarity routes."),
    ("GEO102", "Southern Africa solidarity routes", "GEO061", "REG014", "regional_context", "", "English; Portuguese; Afrikaans; Indigenous languages; others", "Latin", "modern", "Botswana, Zimbabwe, Mozambique, Angola, South Africa, Namibia, and exile/solidarity print networks."),
    ("GEO103", "Indigenous North America", "GEO024", "REG003", "indigenous_context", "", "First Nations; Inuit; Metis; Native American; Alaska Native languages; English; French; Spanish", "Latin; syllabics; Indigenous scripts/orthographies", "modern", "Protocol-aware Indigenous print and community publishing context."),
    ("GEO104", "Aboriginal Australia", "GEO069", "REG015", "indigenous_context", "", "Indigenous Australian languages; English", "Latin; local orthographies", "modern", "Protocol-aware Aboriginal rights graphics, posters, publications, and community materials."),
    ("GEO105", "Torres Strait Islander Australia", "GEO069", "REG015", "indigenous_context", "", "Torres Strait Islander languages; English", "Latin; local orthographies", "modern", "Protocol-aware Torres Strait visual culture and community materials."),
    ("GEO106", "Maori print and language contexts", "GEO070", "REG015", "indigenous_context", "", "Maori; English", "Latin; Maori orthography", "modern", "Niupepa, language revival, public graphics, and bicultural design."),
    ("GEO107", "Melanesia", "GEO071", "REG015", "regional_context", "", "Papuan; Austronesian; English; French; others", "Latin; local orthographies", "modern", "Mission, colonial, postcolonial, community, and public graphics."),
    ("GEO108", "Polynesia", "GEO071", "REG015", "regional_context", "", "Samoan; Tongan; Hawaiian; Tahitian; Maori; English; French; others", "Latin; local orthographies", "modern", "Pacific print routes, language, culture, and diasporic visual communication."),
    ("GEO109", "Micronesia", "GEO071", "REG015", "regional_context", "", "Chamorro; Marshallese; Palauan; English; others", "Latin; local orthographies", "modern", "Colonial/postcolonial media and community visual communication."),
]

geographies.extend(
    {
        "geo_id": row[0],
        "name": row[1],
        "parent_geo_id": row[2],
        "region_id": row[3],
        "geo_type": row[4],
        "iso_code": row[5],
        "language_scope": row[6],
        "script_scope": row[7],
        "date_scope": row[8],
        "notes": row[9],
    }
    for row in geography_audit_seed
)


regional_movements_fields = [
    "regional_movement_id",
    "name",
    "alternate_names",
    "region_id",
    "geo_id",
    "date_start",
    "date_end",
    "date_text",
    "formation_type",
    "related_node_ids",
    "related_movement_ids",
    "key_media",
    "source_needs",
    "rights_risk",
    "status",
    "notes",
]

regional_movement_seed = [
    ("RM001", "British Arts and Crafts book and private press reform", "", "REG001", "GEO003", "1860", "1919", "c.1860s-1910s", "reform/publishing formation", "HN006", "MV001", "books; type; ornaments; journals", "design libraries; rare book collections; exhibition catalogues", "medium", "launch_scope", "Tracks print reform as publishing practice rather than decorative style only."),
    ("RM002", "French affiche and illustrated press culture", "Belle Epoque poster culture", "REG001", "GEO005", "1880", "1914", "c.1880s-1914", "poster/periodical formation", "HN004; HN005; HN006", "MV002", "lithographic posters; magazines; sheet music", "poster museums; Gallica; museum print rooms", "medium", "launch_scope", "Connects Art Nouveau with commercial lithographic mass culture."),
    ("RM003", "German Jugendstil and Sachplakat", "object poster", "REG001", "GEO006", "1890", "1914", "c.1890s-1914", "poster/commercial formation", "HN005; HN006", "MV002", "posters; trademarks; packaging", "poster archives; museum collections; trade press", "medium", "launch_scope", "Requires separation between Jugendstil ornament and Sachplakat commercial simplification."),
    ("RM004", "Vienna Secession publishing and exhibition graphics", "", "REG001", "GEO008", "1897", "1918", "1897-1918", "movement/publishing formation", "HN006", "MV003", "journals; posters; exhibition catalogues", "museum collections; Ver Sacrum records", "medium", "launch_scope", "Use as a specific formation, not a generic Art Nouveau synonym."),
    ("RM005", "Italian Futurist typographic experiment", "parole in liberta", "REG001", "GEO011", "1909", "1939", "1909-1930s", "avant-garde formation", "HN007", "MV005", "manifestos; books; experimental typography", "avant-garde collections; periodical archives", "medium", "launch_scope", "Important for nonlinear page structure and performance of text."),
    ("RM006", "Dutch De Stijl publication and typographic systems", "", "REG001", "GEO009", "1917", "1931", "1917-1931", "avant-garde/publishing formation", "HN007; HN008", "MV007", "journals; manifestos; layouts", "museum collections; periodical scans", "medium", "launch_scope", "Track journal networks and international transmission."),
    ("RM007", "Bauhaus typography and institutional graphics", "", "REG001", "GEO006", "1919", "1933", "1919-1933", "school/design formation", "HN008", "MV011; MV012", "stationery; posters; books; teaching material", "Bauhaus archives; museum collections", "medium", "launch_scope", "Canonical but must be linked outward to exile and reception routes."),
    ("RM008", "Swiss International Typographic Style", "Swiss Style", "REG001", "GEO007", "1945", "1975", "c.1945-1975", "typographic/systems formation", "HN010", "MV014", "posters; grids; manuals; magazines", "Swiss design archives; museum collections", "medium", "launch_scope", "Must not become universal default grid history."),
    ("RM009", "Ulm systems and information design", "HfG Ulm", "REG001", "GEO006", "1953", "1968", "1953-1968", "school/systems formation", "HN010; HN011", "MV015; MV018", "identity systems; pictograms; manuals", "HfG archives; corporate archives; museum collections", "medium", "launch_scope", "Central to systems design and method-oriented design history."),
    ("RM010", "Polish poster school", "Polska Szkola Plakatu", "REG002", "GEO018", "1945", "1989", "c.1945-1989", "poster formation", "HN009; HN010; HN013", "", "posters; film posters; theatre posters", "poster museums; national libraries; film archives", "medium-high", "launch_scope", "Major non-Western-European canonical formation often under-integrated into global timelines."),
    ("RM011", "Russian/Soviet Constructivism and agitprop", "", "REG002", "GEO016", "1917", "1939", "1917-1930s", "avant-garde/state formation", "HN007; HN009", "MV008; MV010", "posters; books; journals; photomontage", "museum collections; periodicals; state archives", "medium", "launch_scope", "Distinguish documented Soviet networks from later stylistic revival."),
    ("RM012", "Czech and Slovak avant-garde publishing", "Devetsil-related print cultures", "REG002", "GEO019", "1920", "1939", "1920s-1930s", "avant-garde/publishing formation", "HN007; HN008", "MV012", "journals; books; photomontage", "national libraries; avant-garde periodicals", "medium", "launch_scope", "Important bridge between avant-garde typography, poetry, and publishing."),
    ("RM013", "Hungarian activist and modernist graphics", "", "REG002", "GEO020", "1910", "1945", "c.1910s-1940s", "avant-garde/political formation", "HN007; HN009", "MV019", "journals; posters; photomontage", "national libraries; museum collections", "medium", "launch_scope", "Requires attention to exile routes and multilingual circulation."),
    ("RM014", "Yugoslav non-aligned design and tourism graphics", "", "REG002", "GEO023", "1945", "1991", "1945-1991", "state/commercial formation", "HN009; HN010; HN011", "", "posters; tourism graphics; identity systems", "national libraries; tourism archives; poster collections", "medium-high", "launch_scope", "Important socialist/non-aligned route outside USSR-centered narratives."),
    ("RM015", "American corporate identity and design management", "", "REG003", "GEO025", "1950", "1989", "c.1950s-1980s", "corporate/systems formation", "HN011", "MV016", "identity manuals; annual reports; signage", "company archives; design archives; trade press", "high", "launch_scope", "High rights risk; link-first indexing preferred."),
    ("RM016", "American editorial modernism and magazine systems", "", "REG003", "GEO025", "1940", "1979", "c.1940s-1970s", "publishing formation", "HN011", "MV017", "magazines; layouts; covers; advertising", "periodical databases; magazine archives", "medium-high", "launch_scope", "Track issue/page metadata and publication context."),
    ("RM017", "Civil rights, Black press, and African diasporic graphics", "", "REG003", "GEO025", "1900", "", "20th c.-present", "counterpublic formation", "HN012", "MV024", "newspapers; posters; flyers; newsletters", "community archives; university special collections; newspaper archives", "high", "launch_scope", "Must not appear only as protest imagery; includes publishing and institution building."),
    ("RM018", "Canadian public information and cultural identity design", "", "REG003", "GEO026", "1950", "1999", "c.1950s-1990s", "state/cultural formation", "HN010; HN011", "MV018", "symbols; posters; identity systems; publications", "national archives; museums; design centers", "medium", "launch_scope", "Needed to prevent North America becoming U.S.-only."),
    ("RM019", "Mexican modern print, Taller, and Olympic identity routes", "", "REG004", "GEO027", "1920", "1989", "c.1920s-1980s", "print/political/systems formation", "HN009; HN010; HN011; HN012", "", "posters; books; identity systems; murals-to-print ephemera", "national libraries; poster collections; Olympic archives", "medium-high", "launch_scope", "Cross-links Latin America and North America."),
    ("RM020", "Cuban revolutionary and film poster culture", "", "REG004", "GEO029", "1959", "1999", "c.1959-1990s", "state/political/poster formation", "HN009; HN012; HN013", "MV021", "film posters; solidarity posters; screenprints", "poster archives; film institutes; museum collections", "high", "launch_scope", "Requires rights-sensitive link-first approach."),
    ("RM021", "Brazilian concrete, visual poetry, and modern design", "", "REG004", "GEO030", "1950", "1989", "c.1950s-1980s", "modernist/typographic formation", "HN010; HN011; HN013", "", "books; posters; identity; visual poetry", "museum collections; university archives; periodicals", "medium", "launch_scope", "Connects graphic design, concrete art, typography, and publishing."),
    ("RM022", "Chilean political poster and solidarity graphics", "", "REG004", "GEO032", "1960", "1990", "c.1960s-1990s", "political/counterpublic formation", "HN009; HN012", "MV021", "posters; flyers; pamphlets", "poster archives; political collections; university archives", "high", "launch_scope", "Must distinguish local production, exile, and international solidarity circulation."),
    ("RM023", "Japanese modern poster and commercial design", "", "REG005", "GEO036", "1900", "1989", "20th c.", "poster/commercial formation", "HN005; HN010; HN011", "", "posters; magazines; packaging; advertising", "National Diet Library; museum collections; design archives", "medium-high", "launch_scope", "Must include prewar, postwar, and commercial mass culture, not only poster masters."),
    ("RM024", "Japanese postwar typography, corporate identity, and packaging", "", "REG005", "GEO036", "1945", "1999", "postwar-1990s", "typographic/corporate formation", "HN010; HN011; HN014", "MV016; MV018", "identity systems; type; packaging; magazines", "design museums; corporate archives; trade journals", "high", "launch_scope", "Multiscript metadata and rights-sensitive corporate material required."),
    ("RM025", "Japanese interface, game, and platform visual cultures", "", "REG005", "GEO036", "1980", "", "c.1980s-present", "digital/platform formation", "HN014; HN015", "MV035; MV036", "interfaces; game graphics; websites; platform templates", "web archives; software archives; company docs", "very high", "launch_scope", "Needs capture date, version, and viewport/platform metadata."),
    ("RM026", "Korean Hangul typography and print modernization", "", "REG006", "GEO037", "1900", "1989", "20th c.", "typographic/print formation", "HN005; HN009; HN010; HN014", "", "type specimens; books; posters; newspapers", "national libraries; typography archives; university repositories", "medium-high", "launch_scope", "Hangul script support is structural, not decorative."),
    ("RM027", "South Korean corporate identity, publishing, and digital design", "", "REG006", "GEO038", "1960", "", "c.1960s-present", "corporate/digital formation", "HN011; HN014; HN015", "MV016; MV035", "identity; magazines; apps; platform graphics", "museum collections; company archives; web archives", "high", "launch_scope", "Important for contemporary platform and brand visual culture."),
    ("RM028", "Chinese Republican Shanghai commercial print", "", "REG008", "GEO040", "1912", "1949", "1912-1949", "commercial/periodical formation", "HN005; HN007", "", "advertising; magazines; calendar posters; packaging", "Shanghai library collections; periodicals; poster archives", "high", "launch_scope", "Do not reduce Chinese modern design to propaganda."),
    ("RM029", "Chinese socialist visual communication and propaganda", "", "REG008", "GEO040", "1949", "1978", "1949-1978", "state communication formation", "HN009; HN012", "MV020", "posters; pamphlets; exhibition graphics; newspapers", "poster collections; national libraries; museum collections", "high", "launch_scope", "Rights and political context must be handled cautiously."),
    ("RM030", "Chinese reform-era commercial design and branding", "", "REG008", "GEO040", "1978", "2010", "c.1978-2010", "commercial/corporate formation", "HN011; HN014", "MV016; MV032", "logos; packaging; advertising; magazines", "periodicals; company archives; design annuals", "high", "launch_scope", "Important bridge from state design to market/platform design."),
    ("RM031", "Chinese platform-native visual communication", "", "REG008", "GEO040", "2010", "", "c.2010s-present", "platform formation", "HN015", "MV036; MV038", "social graphics; app UI; campaign templates", "web archives; platform captures; design-system docs", "very high", "launch_scope", "Index mostly as metadata/link/capture description because reproduction risk is high."),
    ("RM032", "Hong Kong bilingual commercial and film graphics", "", "REG009", "GEO041", "1950", "1999", "c.1950s-1990s", "bilingual/commercial formation", "HN011; HN013", "", "film posters; magazines; advertising; signage", "film archives; university archives; museum collections", "high", "launch_scope", "Bilingual typography and local media specificity are essential."),
    ("RM033", "Hong Kong protest and public graphics", "", "REG009", "GEO041", "1960", "", "c.1960s-present", "counterpublic formation", "HN012; HN015", "MV021", "posters; flyers; social graphics; banners", "community archives; web archives; university collections", "very high", "launch_scope", "Rights, privacy, and political risk are high."),
    ("RM034", "Taiwan postwar publishing, political graphics, and democratization design", "", "REG010", "GEO042", "1945", "2000", "c.1945-2000", "publishing/political formation", "HN009; HN012; HN013", "", "magazines; posters; ballots; campaign graphics", "national libraries; museum archives; periodicals", "high", "launch_scope", "Requires separate treatment from Mainland China and Japan while preserving historical links."),
    ("RM035", "Taiwan contemporary typography, identity, and digital design", "", "REG010", "GEO042", "2000", "", "c.2000s-present", "typographic/digital formation", "HN014; HN015", "MV033; MV035", "type; identity; websites; apps", "web archives; design archives; studio documentation", "high", "launch_scope", "Traditional Chinese support and contemporary rights policies needed."),
    ("RM036", "Indonesian nationalist, commercial, and vernacular print", "", "REG011", "GEO044", "1900", "", "20th c.-present", "print/commercial formation", "HN005; HN009; HN012; HN013", "", "posters; newspapers; packaging; signs", "national libraries; colonial archives; community archives", "high", "launch_scope", "Colonial and postcolonial source separation required."),
    ("RM037", "Singapore/Malaysia multilingual state and commercial graphics", "", "REG011", "GEO045", "1950", "", "c.1950s-present", "multilingual/state/commercial formation", "HN010; HN011; HN015", "MV018", "campaigns; identity; posters; wayfinding; websites", "national libraries; public agencies; web archives", "high", "launch_scope", "Multiscript, multilingual display is a structural test case."),
    ("RM038", "Thai typography, advertising, and publishing", "", "REG011", "GEO046", "1900", "", "20th c.-present", "typographic/commercial formation", "HN005; HN011; HN014; HN015", "", "type; magazines; posters; advertising; websites", "national libraries; periodicals; web archives", "high", "launch_scope", "Requires Thai script metadata and search vocabulary."),
    ("RM039", "Vietnamese colonial, socialist, and contemporary poster/print cultures", "", "REG011", "GEO047", "1900", "", "20th c.-present", "colonial/state/commercial formation", "HN005; HN009; HN012; HN015", "MV020", "posters; newspapers; books; digital graphics", "national libraries; poster collections; colonial archives", "high", "launch_scope", "Must separate French colonial, revolutionary, state, and contemporary commercial contexts."),
    ("RM040", "Philippine political, commercial, and popular graphic cultures", "", "REG011", "GEO048", "1900", "", "20th c.-present", "commercial/political formation", "HN005; HN009; HN012; HN013; HN015", "", "posters; magazines; election graphics; popular media", "national libraries; university archives; web archives", "high", "launch_scope", "English/Filipino/Spanish source layers need careful handling."),
    ("RM041", "Indian multilingual typography and publishing", "", "REG012", "GEO051", "1800", "", "19th c.-present", "typographic/publishing formation", "HN005; HN009; HN014; HN015", "", "books; newspapers; type; posters; websites", "national libraries; type archives; periodicals", "high", "launch_scope", "Multiscript typography is central, not peripheral."),
    ("RM042", "Indian film poster and popular print culture", "", "REG012", "GEO051", "1930", "", "c.1930s-present", "popular/commercial formation", "HN005; HN013; HN015", "MV030", "film posters; lobby cards; calendars; digital promos", "film archives; poster collections; web archives", "high", "launch_scope", "Rights risk is high; link-first metadata preferred."),
    ("RM043", "South Asian state information and political graphics", "", "REG012", "GEO050", "1947", "", "post-1947", "state/political formation", "HN009; HN010; HN012", "MV020; MV018", "posters; public campaigns; ballots; newspapers", "national archives; government publications; community archives", "high", "launch_scope", "Regional split across India, Pakistan, Bangladesh, Sri Lanka and diaspora contexts."),
    ("RM044", "Arabic typography and modern publishing", "", "REG013", "GEO055", "1800", "", "19th c.-present", "typographic/publishing formation", "HN005; HN014; HN015", "", "books; newspapers; type specimens; websites", "national libraries; type archives; periodicals", "high", "launch_scope", "RTL and Arabic-script metadata must be included before design freeze."),
    ("RM045", "Egyptian film poster, publishing, and political graphics", "", "REG013", "GEO056", "1920", "", "c.1920s-present", "popular/political formation", "HN005; HN009; HN013", "", "film posters; magazines; books; campaign graphics", "film archives; national libraries; poster collections", "high", "launch_scope", "Connects MENA popular visual culture with print and political histories."),
    ("RM046", "Iranian modern typography and revolutionary poster cultures", "", "REG013", "GEO057", "1900", "", "20th c.-present", "typographic/political formation", "HN009; HN012; HN014", "MV020; MV021", "posters; books; type; magazines", "national libraries; museum collections; poster archives", "high", "launch_scope", "Requires Persian-script search and rights/political caution."),
    ("RM047", "Turkish script reform and modern graphic design", "", "REG013", "GEO058", "1928", "", "1928-present", "script/state/commercial formation", "HN009; HN010; HN011; HN014", "", "books; posters; identity; magazines", "national libraries; design archives; periodicals", "medium-high", "launch_scope", "Script reform is a historical node, not only a language issue."),
    ("RM048", "Levantine political, publishing, and multilingual graphics", "", "REG013", "GEO059", "1900", "", "20th c.-present", "multilingual/political formation", "HN005; HN009; HN012", "", "posters; magazines; books; solidarity graphics", "university archives; poster collections; national libraries", "high", "launch_scope", "Must handle Arabic, Hebrew, Armenian, French, and English contexts."),
    ("RM049", "African independence-era and decolonial graphics", "", "REG014", "GEO061", "1945", "1980", "c.1945-1980", "political/decolonial formation", "HN009; HN012", "MV025", "posters; newspapers; pamphlets; symbols", "national archives; university collections; political archives", "high", "launch_scope", "Core launch scope due to underrepresentation in mainstream design histories."),
    ("RM050", "South African anti-apartheid and community graphics", "", "REG014", "GEO062", "1950", "1994", "c.1950-1994", "counterpublic formation", "HN009; HN012", "MV021; MV025", "posters; newsletters; banners; community print", "community archives; university collections; poster archives", "high", "launch_scope", "Requires strong context and rights/protocol review."),
    ("RM051", "West African commercial signs, posters, publishing, and film graphics", "", "REG014", "GEO066", "1950", "", "c.1950s-present", "vernacular/commercial formation", "HN005; HN013; HN015", "MV030", "signs; posters; film graphics; advertising; websites", "community archives; newspaper archives; web archives", "high", "launch_scope", "Vernacular material must not be treated as lower-value evidence."),
    ("RM052", "Nigerian publishing, advertising, and Nollywood graphics", "", "REG014", "GEO063", "1960", "", "c.1960s-present", "commercial/popular formation", "HN005; HN013; HN015", "MV030; MV036", "magazines; posters; video covers; social graphics", "national libraries; film archives; web archives", "high", "launch_scope", "Important for popular media and platform visual cultures."),
    ("RM053", "Australian public information, publishing, and protest graphics", "", "REG015", "GEO069", "1900", "", "20th c.-present", "state/publishing/counterpublic formation", "HN009; HN010; HN012; HN015", "MV018; MV021", "posters; publications; public campaigns; websites", "Trove; national archives; community archives; web archives", "high", "launch_scope", "Includes Indigenous protocols and community archive boundaries."),
    ("RM054", "Aotearoa New Zealand bicultural and public graphic design", "", "REG015", "GEO070", "1950", "", "c.1950s-present", "public/bicultural formation", "HN010; HN011; HN012; HN015", "MV018; MV025", "identity; signage; publications; campaign graphics", "DigitalNZ; national libraries; public agencies; community archives", "high", "launch_scope", "Must support Maori language, protocol, and bicultural design context."),
    ("RM055", "Pacific community, cultural, and public visual communication", "", "REG015", "GEO071", "1950", "", "c.1950s-present", "community/regional formation", "HN012; HN013; HN015", "MV025; MV030", "posters; festival graphics; publications; social graphics", "community archives; national libraries; web archives", "high", "launch_scope", "Source and cultural protocol gaps should be exposed, not hidden."),
]

regional_movements = [
    {
        "regional_movement_id": row[0],
        "name": row[1],
        "alternate_names": row[2],
        "region_id": row[3],
        "geo_id": row[4],
        "date_start": row[5],
        "date_end": row[6],
        "date_text": row[7],
        "formation_type": row[8],
        "related_node_ids": row[9],
        "related_movement_ids": row[10],
        "key_media": row[11],
        "source_needs": row[12],
        "rights_risk": row[13],
        "status": row[14],
        "notes": row[15],
    }
    for row in regional_movement_seed
]

regional_movement_audit_seed = [
    ("RM056", "Arabic periodical modernity", "", "REG013", "GEO055", "1800", "", "19th c.-present", "editorial/script formation", "HN005; HN014; HN015", "RM044", "newspapers; magazines; type; books; digital periodicals", "Arabic newspaper archives; national libraries; periodicals", "high", "launch_scope", "Added from Global Coverage Audit; Arabic periodical and typographic modernization is structural."),
    ("RM057", "Iran modern graphic design and Persian publishing", "", "REG013", "GEO083", "1950", "1979", "c.1950-1979", "professional/publishing formation", "HN010; HN011; HN014", "RM046", "books; posters; magazines; type", "NLAI; periodicals; museum collections", "high", "launch_scope", "Separates Iranian modernist/publishing circuits from broader MENA."),
    ("RM058", "Iran postrevolutionary public graphics", "", "REG013", "GEO083", "1979", "", "1979-present", "state/political formation", "HN009; HN012; HN014", "RM046", "posters; public campaigns; magazines; digital graphics", "NLAI; poster collections; periodicals", "high", "launch_scope", "Post-1979 public graphics and poster regimes require separate tracking."),
    ("RM059", "Soviet script reform in Central Asia", "Latinization; Cyrillicization", "REG002", "GEO072", "1920", "1940", "c.1920s-1940s", "script/state formation", "HN009; HN014", "", "schoolbooks; newspapers; alphabets; public information", "national libraries; legal deposit; periodicals", "medium", "launch_scope", "Script reform changes search, typography, and identity metadata."),
    ("RM060", "Pakistan Urdu commercial graphics", "", "REG012", "GEO052", "1947", "", "1947-present", "commercial/script formation", "HN005; HN011; HN014; HN015", "", "newspapers; posters; packaging; film graphics; digital", "national libraries; periodicals; film archives", "high", "launch_scope", "Urdu script and commercial/popular graphics beyond India."),
    ("RM061", "Bangladesh language movement graphics", "", "REG012", "GEO053", "1952", "", "1952-present", "language/political formation", "HN009; HN012; HN014", "", "posters; newspapers; language movement ephemera; memorial graphics", "national archives; periodicals; community archives", "high", "launch_scope", "Language politics and Bengali script are central to design history."),
    ("RM062", "South Asian vernacular packaging and magazines", "", "REG012", "GEO050", "1900", "", "20th c.-present", "vernacular/commercial formation", "HN005; HN011; HN013", "MV030", "packaging; magazines; calendars; advertisements", "periodicals; market ephemera; digitized books", "high", "launch_scope", "Prevents South Asia from being represented only through state or film posters."),
    ("RM063", "Singapore campaign poster regime", "", "REG011", "GEO095", "1965", "", "1965-present", "state/public information formation", "HN009; HN010; HN011", "MV018; MV020", "campaign posters; public information; multilingual graphics", "NLB; NAS; government archives; web archives", "high", "launch_scope", "Multilingual state campaign design is structurally important."),
    ("RM064", "Jawi-Rumi Malay print transition", "", "REG011", "GEO096", "1900", "1970", "c.1900-1970", "script/print formation", "HN005; HN009; HN014", "", "newspapers; books; campaign print; typography", "NLB; national libraries; periodicals", "medium-high", "launch_scope", "Models script transition and search implications in Malay print."),
    ("RM065", "Vietnam propaganda to Doi Moi design", "", "REG011", "GEO047", "1945", "", "1945-present", "state/commercial transition formation", "HN009; HN011; HN012; HN015", "RM039", "posters; newspapers; advertising; digital graphics", "Vietnamese national/museum archives; periodicals", "high", "launch_scope", "Separates revolutionary/state design from post-1986 market transition."),
    ("RM066", "Indonesian revolutionary and state graphics", "", "REG011", "GEO044", "1945", "1998", "1945-1998", "state/political formation", "HN009; HN012", "RM036", "posters; newspapers; public campaigns", "Perpusnas; colonial archives; national archives", "high", "launch_scope", "Adds independence and state visual communication to Indonesian coverage."),
    ("RM067", "Philippine komiks and film print", "", "REG011", "GEO048", "1930", "", "c.1930s-present", "popular/commercial formation", "HN005; HN013; HN015", "RM040", "komiks; film posters; magazines; social graphics", "national libraries; film archives; periodicals", "high", "launch_scope", "Popular print cultures should not be secondary to museum-held posters."),
    ("RM068", "Taller de Grafica Popular and Mexican popular print", "TGP", "REG004", "GEO027", "1937", "", "1937-present influence", "workshop/political print formation", "HN009; HN012; HN013", "MV021; RM019", "prints; posters; pamphlets; workshop records", "museum collections; TGP archives; political print collections", "medium-high", "launch_scope", "Dateable political print formation with global solidarity connections."),
    ("RM069", "Chilean editorial and film magazine design", "", "REG004", "GEO032", "1905", "1990", "c.1905-1990", "editorial/popular formation", "HN005; HN011; HN013", "", "magazines; film press; editorial layouts", "Memoria Chilena; periodical archives", "medium-high", "launch_scope", "Expands Chile beyond political poster-only framing."),
    ("RM070", "Caribbean music, carnival, and tourism graphics", "", "REG004", "GEO034", "1940", "", "c.1940s-present", "popular/commercial formation", "HN005; HN011; HN013; HN015", "", "record sleeves; posters; brochures; newspapers; social graphics", "dLOC; national libraries; music archives; tourism archives", "high", "launch_scope", "Caribbean graphic culture is not reducible to revolution/posters."),
    ("RM071", "Southern Africa anti-apartheid workshop graphics", "", "REG014", "GEO102", "1970", "1994", "c.1970-1994", "workshop/counterpublic formation", "HN009; HN012", "RM050; MV021", "posters; newsletters; workshop prints; solidarity graphics", "SAHA; DISA; African Activist Archive; community archives", "high", "launch_scope", "Adds workshop/network structure to anti-apartheid graphics."),
    ("RM072", "Maori niupepa and language print", "", "REG015", "GEO106", "1842", "", "1842-present", "language/publishing formation", "HN005; HN012; HN014", "RM054", "newspapers; public graphics; language revival print", "Papers Past; national libraries; community archives", "high", "launch_scope", "Maori-language print requires source-language and protocol-aware modeling."),
    ("RM073", "Aboriginal rights graphics", "", "REG015", "GEO104", "1960", "", "c.1960s-present", "Indigenous/counterpublic formation", "HN012; HN013; HN015", "MV025; RM053", "posters; campaign graphics; community publications; web records", "AIATSIS; community archives; Trove; web archives", "high", "launch_scope", "Protocol-sensitive rights and community metadata are central."),
    ("RM074", "East Asia editorial and platform design", "", "REG007", "GEO035", "1990", "", "c.1990s-present", "digital/editorial/platform formation", "HN014; HN015", "MV035; MV036; RM025; RM027; RM031; RM035", "websites; apps; social graphics; editorial platforms", "web archives; platform captures; design-system docs", "very high", "launch_scope", "Cross-regional East Asian digital visual culture needs explicit treatment."),
]

regional_movements.extend(
    {
        "regional_movement_id": row[0],
        "name": row[1],
        "alternate_names": row[2],
        "region_id": row[3],
        "geo_id": row[4],
        "date_start": row[5],
        "date_end": row[6],
        "date_text": row[7],
        "formation_type": row[8],
        "related_node_ids": row[9],
        "related_movement_ids": row[10],
        "key_media": row[11],
        "source_needs": row[12],
        "rights_risk": row[13],
        "status": row[14],
        "notes": row[15],
    }
    for row in regional_movement_audit_seed
)


regional_event_nodes_fields = [
    "event_node_id",
    "event_name",
    "event_type",
    "region_id",
    "geo_id",
    "date_start",
    "date_end",
    "date_text",
    "related_node_ids",
    "related_regional_movement_ids",
    "source_need",
    "rights_risk",
    "status",
    "notes",
]

regional_event_seed = [
    ("REN001", "Lithography enters industrial public display and poster culture", "technology/circulation node", "REG001", "GEO002", "1796", "1914", "c.1796-1914", "HN004; HN005", "RM002; RM003", "poster archives; print histories; museum records", "medium", "launch_scope", "Technical node that links Europe to later global poster cultures."),
    ("REN002", "Arts and Crafts and private press reform becomes a graphic design precursor", "movement node", "REG001", "GEO003", "1860", "1919", "c.1860s-1910s", "HN006", "RM001", "rare book collections; design libraries", "medium", "launch_scope", "Treat as pre-professional graphic design evidence."),
    ("REN003", "Art Nouveau/Jugendstil/Secession graphic systems spread through posters and magazines", "movement/circulation node", "REG001", "GEO002", "1880", "1914", "c.1880s-1914", "HN006", "RM002; RM003; RM004", "poster collections; periodicals", "medium", "launch_scope", "Multi-country formation, not a single style label."),
    ("REN004", "Avant-garde journals and manifestos reshape page space", "publication node", "REG001", "GEO002", "1909", "1935", "1909-1935", "HN007", "RM005; RM006", "avant-garde periodicals; manifesto collections", "medium", "launch_scope", "Connects Futurism, Dada, De Stijl, and related print experiments."),
    ("REN005", "Bauhaus institutional graphic identity and New Typography transmission", "school/transmission node", "REG001", "GEO006", "1919", "1938", "1919-1938", "HN008", "RM007", "school archives; modernist publishing records", "medium", "launch_scope", "Must index exile and reception routes."),
    ("REN006", "Postwar Swiss/Ulm systems become a global reference for grids and information design", "systems node", "REG001", "GEO007", "1945", "1975", "c.1945-1975", "HN010", "RM008; RM009", "design archives; transit/civic archives", "medium", "launch_scope", "Use as one route among many systems histories."),
    ("REN007", "Russian Revolution, Constructivism, and Soviet agitational print converge", "political/avant-garde node", "REG002", "GEO016", "1917", "1939", "1917-1930s", "HN007; HN009", "RM011", "museum collections; periodicals; state archives", "medium", "launch_scope", "Separate documented networks from aesthetic resemblance."),
    ("REN008", "Central/Eastern European avant-garde publishing and photomontage networks", "publication/transnational node", "REG002", "GEO015", "1920", "1939", "1920s-1930s", "HN007; HN008", "RM012; RM013", "national libraries; university collections", "medium", "launch_scope", "Important for non-Western-European modernism."),
    ("REN009", "Postwar Polish poster school and socialist-era poster cultures", "poster node", "REG002", "GEO018", "1945", "1989", "c.1945-1989", "HN009; HN013", "RM010", "poster museums; film/theatre archives", "medium-high", "launch_scope", "Track cultural posters, film posters, and state/cultural institutions."),
    ("REN010", "Yugoslav non-aligned visual culture and tourism/state design", "state/commercial node", "REG002", "GEO023", "1945", "1991", "1945-1991", "HN010; HN011", "RM014", "national libraries; tourism archives", "medium-high", "launch_scope", "Prevents socialist design from being USSR-only."),
    ("REN011", "U.S. advertising, editorial design, and corporate identity professionalization", "professionalization node", "REG003", "GEO025", "1920", "1989", "c.1920s-1980s", "HN005; HN011", "RM015; RM016", "trade press; company archives; periodicals", "high", "launch_scope", "High digitization should not overdetermine global importance."),
    ("REN012", "Civil rights, feminist, queer, labor, and Black press graphics expand the archive", "counterpublic node", "REG003", "GEO025", "1900", "", "20th c.-present", "HN012; HN013", "RM017", "community archives; newspapers; zine archives", "high", "launch_scope", "Counterpublic and community sources are launch-structural."),
    ("REN013", "Canadian identity, public information, and cultural design contexts", "public/cultural node", "REG003", "GEO026", "1950", "1999", "c.1950s-1990s", "HN010; HN011", "RM018", "national archives; museums; design centers", "medium", "launch_scope", "Separates Canadian design history from U.S. frameworks."),
    ("REN014", "Mexican revolutionary/post-revolutionary print and Olympic identity routes", "political/systems node", "REG004", "GEO027", "1920", "1968", "c.1920-1968", "HN009; HN010; HN011; HN012", "RM019", "national libraries; Olympic archives; poster collections", "medium-high", "launch_scope", "Important crossroad for print, national identity, and systems design."),
    ("REN015", "Cuban film, revolutionary, and solidarity poster production", "poster/political node", "REG004", "GEO029", "1959", "1999", "c.1959-1990s", "HN009; HN012; HN013", "RM020", "poster archives; film institutes", "high", "launch_scope", "Rights-sensitive and often internationally circulated."),
    ("REN016", "Brazilian concrete/modernist graphics link typography, visual poetry, and identity", "modernist/typographic node", "REG004", "GEO030", "1950", "1989", "c.1950s-1980s", "HN010; HN011; HN013", "RM021", "museum collections; periodicals", "medium", "launch_scope", "Important non-Euro-American modernist route."),
    ("REN017", "Latin American anti-dictatorship, exile, and solidarity graphics", "counterpublic/transnational node", "REG004", "GEO028", "1960", "1990", "c.1960s-1990s", "HN009; HN012", "RM022", "political archives; community collections", "high", "launch_scope", "Separate local production from exile/international solidarity circulation."),
    ("REN018", "Japanese postwar poster, corporate, packaging, and multiscript design", "commercial/typographic node", "REG005", "GEO036", "1945", "1999", "postwar-1990s", "HN010; HN011; HN014", "RM023; RM024", "design archives; museum collections; trade journals", "high", "launch_scope", "Japan must be a core structure, not a case study."),
    ("REN019", "Japanese digital, game, interface, and platform visual culture", "digital node", "REG005", "GEO036", "1980", "", "c.1980s-present", "HN014; HN015", "RM025", "web archives; software archives; company documentation", "very high", "launch_scope", "Requires born-digital capture rules."),
    ("REN020", "Hangul typography and Korean print modernization", "typographic node", "REG006", "GEO037", "1900", "1989", "20th c.", "HN005; HN014", "RM026", "national libraries; typography archives", "medium-high", "launch_scope", "Script-specific design history must be first-class."),
    ("REN021", "South Korean corporate, publishing, protest, and platform graphics", "commercial/digital node", "REG006", "GEO038", "1960", "", "c.1960s-present", "HN011; HN012; HN015", "RM027", "design archives; web archives; community archives", "high", "launch_scope", "Connects print modernization to platform visual culture."),
    ("REN022", "Republican Shanghai commercial print and magazine culture", "commercial/periodical node", "REG008", "GEO040", "1912", "1949", "1912-1949", "HN005; HN007", "RM028", "periodicals; libraries; poster collections", "high", "launch_scope", "Core for Chinese modern graphic design beyond propaganda."),
    ("REN023", "PRC socialist visual communication, public campaigns, and propaganda", "state communication node", "REG008", "GEO040", "1949", "1978", "1949-1978", "HN009", "RM029", "poster collections; newspapers; state publications", "high", "launch_scope", "Rights and political context must be explicit."),
    ("REN024", "Chinese reform-era commercial design, design education, and brand systems", "commercial/professional node", "REG008", "GEO040", "1978", "2010", "c.1978-2010", "HN011; HN014", "RM030", "design annuals; periodicals; company records", "high", "launch_scope", "Connects market reform to graphic design professionalization."),
    ("REN025", "Chinese platform-native interface, social, and algorithmic visual communication", "platform node", "REG008", "GEO040", "2010", "", "c.2010s-present", "HN015", "RM031", "web archives; app captures; source links", "very high", "launch_scope", "Metadata-first indexing; avoid copying platform content."),
    ("REN026", "Hong Kong bilingual film, advertising, and protest graphic cultures", "bilingual/local media node", "REG009", "GEO041", "1950", "", "c.1950s-present", "HN011; HN012; HN013; HN015", "RM032; RM033", "film archives; university archives; community/web archives", "very high", "launch_scope", "Local context is not reducible to China/UK frameworks."),
    ("REN027", "Taiwan postwar, democratization, and contemporary graphic design", "publishing/political/digital node", "REG010", "GEO042", "1945", "", "1945-present", "HN009; HN012; HN014; HN015", "RM034; RM035", "national libraries; periodicals; web archives", "high", "launch_scope", "Requires Japanese colonial, postwar, and contemporary layers."),
    ("REN028", "Southeast Asian colonial print, independence, and multilingual public graphics", "regional print/state node", "REG011", "GEO043", "1900", "", "20th c.-present", "HN005; HN009; HN012; HN015", "RM036; RM037; RM038; RM039; RM040", "national libraries; colonial archives; community archives", "high", "launch_scope", "This node exists to prevent Southeast Asia from being a later add-on."),
    ("REN029", "Indian multilingual typography, publishing, state design, and popular print", "multiscript node", "REG012", "GEO051", "1800", "", "19th c.-present", "HN005; HN009; HN014; HN015", "RM041; RM042; RM043", "national libraries; film archives; typography archives", "high", "launch_scope", "Multiscript metadata shapes the archive system itself."),
    ("REN030", "South Asian political, film, and multilingual design beyond India", "regional multiscript node", "REG012", "GEO050", "1947", "", "post-1947", "HN009; HN012; HN013; HN015", "RM043", "national archives; community archives; periodicals", "high", "launch_scope", "Pakistan, Bangladesh, Sri Lanka, Nepal and diaspora contexts must not disappear."),
    ("REN031", "Arabic/Persian/Hebrew/Turkish typography and publishing as modern graphic design infrastructure", "script/typography node", "REG013", "GEO055", "1800", "", "19th c.-present", "HN005; HN014; HN015", "RM044; RM046; RM047; RM048", "national libraries; type archives; periodicals", "high", "launch_scope", "RTL and script fields are database requirements."),
    ("REN032", "MENA film, political poster, revolutionary, and postcolonial graphics", "political/popular node", "REG013", "GEO055", "1920", "", "c.1920s-present", "HN009; HN012; HN013", "RM045; RM046; RM048", "poster archives; film archives; university collections", "high", "launch_scope", "Must not be represented only through conflict imagery."),
    ("REN033", "African independence, anti-apartheid, publishing, and vernacular commercial graphics", "decolonial/commercial node", "REG014", "GEO061", "1945", "", "c.1945-present", "HN009; HN012; HN013; HN015", "RM049; RM050; RM051; RM052", "national archives; community archives; web archives", "high", "launch_scope", "Africa must be decomposed and represented as methodologically central."),
    ("REN034", "Australian and Aotearoa public, Indigenous, protest, and web/archive graphics", "public/community node", "REG015", "GEO068", "1900", "", "20th c.-present", "HN009; HN010; HN012; HN015", "RM053; RM054", "Trove; DigitalNZ; community archives; web archives", "high", "launch_scope", "Cultural protocols and rights display are structural."),
    ("REN035", "Pacific community and diasporic visual communication", "community/diaspora node", "REG015", "GEO071", "1950", "", "c.1950s-present", "HN012; HN013; HN015", "RM055", "community archives; web archives; national libraries", "high", "launch_scope", "Expose source gaps and protocols rather than hiding sparse digitization."),
]

regional_event_nodes = [
    {
        "event_node_id": row[0],
        "event_name": row[1],
        "event_type": row[2],
        "region_id": row[3],
        "geo_id": row[4],
        "date_start": row[5],
        "date_end": row[6],
        "date_text": row[7],
        "related_node_ids": row[8],
        "related_regional_movement_ids": row[9],
        "source_need": row[10],
        "rights_risk": row[11],
        "status": row[12],
        "notes": row[13],
    }
    for row in regional_event_seed
]

regional_event_audit_seed = [
    ("REN036", "Taller de Grafica Popular founded in Mexico City", "workshop/political print node", "REG004", "GEO027", "1937", "1937", "1937", "HN009; HN012; HN013", "RM068", "TGP archives; museum collections; political print collections", "medium-high", "launch_scope", "Dateable anchor for Mexican popular/political print and global solidarity graphics."),
    ("REN037", "Bengali/Bangla Language Movement visual culture", "language/political node", "REG012", "GEO053", "1952", "1952", "1952", "HN009; HN012; HN014", "RM061", "Bangladesh archives; newspapers; memorial and language movement collections", "high", "launch_scope", "Language/script politics as graphic design history."),
    ("REN038", "Bandung Conference and Afro-Asian solidarity visual networks", "transnational/political node", "REG011", "GEO044", "1955", "1955", "1955", "HN009; HN012", "RM049; RM066", "UNESCO/MoW records; newspapers; poster and solidarity archives", "high", "launch_scope", "Anti-colonial transnational route across Asia and Africa."),
    ("REN039", "ICAIC foundation and Cuban film poster culture", "film/poster node", "REG004", "GEO029", "1959", "1959", "1959", "HN009; HN012; HN013", "RM020", "film institutes; poster archives; museum collections", "high", "launch_scope", "Dateable institutional anchor for Cuban film poster graphics."),
    ("REN040", "National Institute of Design established in India", "design education node", "REG012", "GEO051", "1961", "1961", "1961", "HN010; HN011; HN014", "RM041; RM043", "NID Archives; design education records; publications", "medium-high", "launch_scope", "Major design education and state-development anchor."),
    ("REN041", "Singapore public campaign poster phase", "state/public information node", "REG011", "GEO095", "1965", "", "c.1965-present", "HN009; HN010; HN011", "RM063", "NLB; NAS; government campaign records; newspapers", "high", "launch_scope", "Multilingual state campaign design anchor."),
    ("REN042", "Zig-Zag magazine launch in Chile", "editorial/popular media node", "REG004", "GEO032", "1905", "1905", "1905", "HN005; HN011; HN013", "RM069", "Memoria Chilena; periodical archives", "medium-high", "launch_scope", "Editorial and magazine design anchor beyond poster history."),
    ("REN043", "Aboriginal Tent Embassy and rights graphics", "Indigenous/counterpublic node", "REG015", "GEO104", "1972", "1972", "1972", "HN012; HN013", "RM073", "AIATSIS; Trove; community archives; newspapers", "high", "launch_scope", "Protocol-sensitive Indigenous rights visual culture anchor."),
    ("REN044", "Medu Art Ensemble and culture/resistance network", "workshop/solidarity node", "REG014", "GEO102", "1982", "1982", "1982", "HN009; HN012", "RM071", "SAHA; DISA; African Activist Archive; workshop records", "high", "launch_scope", "Southern African anti-apartheid workshop/network anchor."),
    ("REN045", "Iranian Revolution public graphics", "revolutionary/public graphics node", "REG013", "GEO083", "1979", "1979", "1979", "HN009; HN012; HN014", "RM058", "NLAI; poster collections; periodicals", "high", "launch_scope", "Dateable postrevolutionary public graphics anchor."),
    ("REN046", "Doi Moi media and commercial design transition", "state/commercial transition node", "REG011", "GEO047", "1986", "1986", "1986", "HN011; HN014; HN015", "RM065", "Vietnamese archives; newspapers; advertising and web records", "high", "launch_scope", "Vietnamese transition from state visual communication to market/digital design."),
    ("REN047", "Korea OASIS web archiving begins", "web archive/digital preservation node", "REG006", "GEO038", "2004", "2004", "2004", "HN015", "RM027", "OASIS Korea; web archive documentation", "high", "launch_scope", "Born-digital preservation anchor for Korean web/interface culture."),
    ("REN048", "Early Maori newspaper phase", "Indigenous/language print node", "REG015", "GEO106", "1842", "", "c.1842 onward", "HN005; HN012; HN014", "RM072", "Papers Past; national libraries; Maori newspaper collections", "high", "launch_scope", "Early source-language print anchor for Maori niupepa and language design."),
]

regional_event_nodes.extend(
    {
        "event_node_id": row[0],
        "event_name": row[1],
        "event_type": row[2],
        "region_id": row[3],
        "geo_id": row[4],
        "date_start": row[5],
        "date_end": row[6],
        "date_text": row[7],
        "related_node_ids": row[8],
        "related_regional_movement_ids": row[9],
        "source_need": row[10],
        "rights_risk": row[11],
        "status": row[12],
        "notes": row[13],
    }
    for row in regional_event_audit_seed
)


def main() -> None:
    write_csv(DATA / "classification_axes.csv", classification_axes_fields, classification_axes)
    write_csv(DATA / "geographies.csv", geographies_fields, geographies)
    write_csv(DATA / "regional_movements.csv", regional_movements_fields, regional_movements)
    write_csv(DATA / "regional_event_nodes.csv", regional_event_nodes_fields, regional_event_nodes)


if __name__ == "__main__":
    main()
