from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


historical_nodes_fields = [
    "node_id",
    "node_name",
    "date_start",
    "date_end",
    "date_text",
    "geo_centers",
    "transnational_routes",
    "associated_formations",
    "key_media_technologies",
    "key_object_types",
    "key_people",
    "key_institutions",
    "likely_source_types",
    "search_keywords",
    "required_metadata_fields",
    "rights_risk_level",
    "underdocumented_notes",
    "editorial_note",
    "source_basis_note",
]

historical_nodes = [
    {
        "node_id": "HN001",
        "node_name": "Writing, inscription, manuscript, early reproduction",
        "date_start": "-3000",
        "date_end": "1450",
        "date_text": "Antiquity-c.1450",
        "geo_centers": "Mesopotamia; Mediterranean; East Asia; Islamic manuscript cultures",
        "transnational_routes": "Trade routes; religious and administrative manuscript circulation",
        "associated_formations": "Scribal cultures; calligraphic traditions; manuscript illumination",
        "key_media_technologies": "Hand inscription; papyrus; parchment; codex; East Asian woodblock",
        "key_object_types": "Tablets; manuscripts; scrolls; seals; diagrams",
        "key_people": "",
        "key_institutions": "Scriptoria; court ateliers; religious institutions",
        "likely_source_types": "Museum collections; manuscript libraries; special collections",
        "search_keywords": "inscription; manuscript; calligraphy; codex; blockbook",
        "required_metadata_fields": "title; script; language; place; date_text; material; support; scribe; repository",
        "rights_risk_level": "Low-medium",
        "underdocumented_notes": "Essential as precondition but not graphic design in the modern disciplinary sense.",
        "editorial_note": "Use as background node, not as the main modern graphic design scope.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN002",
        "node_name": "Printing and movable type",
        "date_start": "1450",
        "date_end": "1800",
        "date_text": "c.1450-1800",
        "geo_centers": "Mainz; Venice; Antwerp; London; East Asia",
        "transnational_routes": "Transatlantic print networks; parallel East Asian type and block traditions",
        "associated_formations": "Early print culture; humanist typography; Reformation print",
        "key_media_technologies": "Movable type; relief printing; letterpress",
        "key_object_types": "Broadsides; pamphlets; books; type specimens; almanacs",
        "key_people": "Gutenberg-associated print culture",
        "key_institutions": "Plantin-Moretus; early foundries; presses",
        "likely_source_types": "Rare book libraries; type collections; bibliographies; museum print rooms",
        "search_keywords": "movable type; incunable; broadside; specimen; presswork",
        "required_metadata_fields": "imprint; printer; publisher; place; edition; format; typeface; language",
        "rights_risk_level": "Low",
        "underdocumented_notes": "Non-European and parallel printing histories must not be folded into a Eurocentric origin story.",
        "editorial_note": "Precondition node for modern graphic design.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN003",
        "node_name": "Engraving, etching, reproductive print",
        "date_start": "1500",
        "date_end": "1900",
        "date_text": "c.1500-1900",
        "geo_centers": "Germany; Netherlands; France; Britain; Italy",
        "transnational_routes": "Print trade and illustrated book circulation",
        "associated_formations": "Printmaking and illustration regimes",
        "key_media_technologies": "Copper engraving; etching; woodcut; steel engraving",
        "key_object_types": "Illustrated books; maps; advertisements; satirical prints",
        "key_people": "",
        "key_institutions": "Print workshops; publishers; mapmakers",
        "likely_source_types": "Print rooms; map libraries; illustrated press collections",
        "search_keywords": "engraving; etching; illustrated press; trade card",
        "required_metadata_fields": "process; plate maker; image maker; publisher; dimensions; print state",
        "rights_risk_level": "Low",
        "underdocumented_notes": "Trade ephemera and commercial engravings are often less cataloged than fine-art prints.",
        "editorial_note": "Useful bridge between print history and commercial visual communication.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN004",
        "node_name": "Lithography and chromolithography",
        "date_start": "1796",
        "date_end": "1919",
        "date_text": "c.1796-1910s",
        "geo_centers": "Munich; Paris; London; New York",
        "transnational_routes": "Global industrial transfer",
        "associated_formations": "Poster culture; illustrated advertising; packaging print",
        "key_media_technologies": "Lithography; chromolithography; transfer printing",
        "key_object_types": "Posters; labels; packaging; sheet music covers; trade cards",
        "key_people": "",
        "key_institutions": "Lithographic printers; advertising houses; illustrated periodicals",
        "likely_source_types": "Poster archives; museum APIs; trade-catalog and ephemera collections",
        "search_keywords": "lithograph; chromolithograph; affiche; label; trade card",
        "required_metadata_fields": "printer; process; color count; client; publisher; edition; condition",
        "rights_risk_level": "Medium",
        "underdocumented_notes": "Commercial labels, wrappers, and packaging are scattered across ephemera collections.",
        "editorial_note": "Core node for industrial visual culture and public display.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN005",
        "node_name": "Nineteenth-century commercial print ecology",
        "date_start": "1830",
        "date_end": "1914",
        "date_text": "c.1830-1914",
        "geo_centers": "Paris; London; New York; Berlin; Vienna",
        "transnational_routes": "Colonial trade routes; illustrated press circulation",
        "associated_formations": "Advertising cultures; illustrated press; department-store print",
        "key_media_technologies": "Steam printing; halftone; mass periodicals",
        "key_object_types": "Posters; newspapers; magazines; catalogues; packaging; newspaper ads",
        "key_people": "",
        "key_institutions": "Newspapers; illustrated magazines; printers; publishers; department stores",
        "likely_source_types": "Newspaper archives; periodical databases; museum collections; HathiTrust; Internet Archive",
        "search_keywords": "illustrated press; advertising; catalogue; packaging; newspaper advertisement",
        "required_metadata_fields": "periodical title; issue; issue_date; page; advertiser; product; publisher",
        "rights_risk_level": "Medium",
        "underdocumented_notes": "Packaging, women's press, vernacular job printing, colonial and multilingual commercial print need explicit inclusion.",
        "editorial_note": "Important evidence field for design before professionalized graphic design.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN006",
        "node_name": "Arts and Crafts, Art Nouveau, Jugendstil, Secession, reform",
        "date_start": "1880",
        "date_end": "1914",
        "date_text": "c.1880s-1914",
        "geo_centers": "Britain; Belgium; France; Austria; Germany; Glasgow",
        "transnational_routes": "U.S. routes via exhibitions and publishing",
        "associated_formations": "Arts and Crafts; Art Nouveau; Jugendstil; Vienna Secession",
        "key_media_technologies": "Letterpress; lithography; ornamental type; integrated design",
        "key_object_types": "Books; journals; posters; interiors graphics; exhibition graphics",
        "key_people": "William Morris circles; Charles R. Mackintosh; Henry van de Velde",
        "key_institutions": "Secession journals; design libraries; exhibition societies",
        "likely_source_types": "Museum collections; exhibition catalogues; design libraries",
        "search_keywords": "arts and crafts; art nouveau; jugendstil; secession; reform",
        "required_metadata_fields": "movement; school; city; publication; designer; ornament; typography",
        "rights_risk_level": "Medium",
        "underdocumented_notes": "Women designers, craft labor, and non-metropolitan reform print cultures remain under-indexed.",
        "editorial_note": "Node joins design reform, ornament, publishing, and poster cultures.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN007",
        "node_name": "Avant-garde rupture and experiment",
        "date_start": "1909",
        "date_end": "1935",
        "date_text": "c.1909-1935",
        "geo_centers": "Italy; Zurich; Berlin; Paris; Moscow; Petrograd; Leiden; Warsaw",
        "transnational_routes": "Avant-garde journals; manifestos; exhibitions; political networks",
        "associated_formations": "Futurism; Dada; De Stijl; Constructivism; Suprematism; Productivism; photomontage",
        "key_media_technologies": "Letterpress; collage; photomontage; experimental typography",
        "key_object_types": "Manifestos; magazines; books; posters; political graphics",
        "key_people": "Marinetti networks; Tristan Tzara; El Lissitzky; Rodchenko; Klutsis; Stenberg brothers",
        "key_institutions": "",
        "likely_source_types": "Museum collections; avant-garde periodical scans; exhibition archives",
        "search_keywords": "futurism; dada; de stijl; constructivism; suprematism; productivism; photomontage",
        "required_metadata_fields": "movement; issue; manifesto; contributor; relation_type; documented_source",
        "rights_risk_level": "Medium",
        "underdocumented_notes": "The archive must separate formal resemblance from documented network ties.",
        "editorial_note": "Core node for typographic experiment and political modernism.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN008",
        "node_name": "Bauhaus, New Typography, modernist books and magazines",
        "date_start": "1919",
        "date_end": "1938",
        "date_text": "c.1919-1938",
        "geo_centers": "Weimar; Dessau; Berlin; Zurich; Prague; Amsterdam; London",
        "transnational_routes": "Exile routes and diasporic transmission",
        "associated_formations": "Bauhaus; New Typography; functional modernism",
        "key_media_technologies": "Sans typography; asymmetric layout; photography; standardized formats",
        "key_object_types": "Books; stationery; posters; exhibition matter; teaching material",
        "key_people": "Herbert Bayer; Jan Tschichold; Moholy-Nagy",
        "key_institutions": "Bauhaus; modernist publishers",
        "likely_source_types": "School archives; museum collections; special collections",
        "search_keywords": "bauhaus; new typography; asymmetry; sans serif; modernist layout",
        "required_metadata_fields": "school; course; teacher; student; publication; edition; printer",
        "rights_risk_level": "Medium",
        "underdocumented_notes": "Transmission into Britain, the U.S., Latin America, and elsewhere should be indexed as relations, not assumed.",
        "editorial_note": "Canonical node, but must be linked outward to transmission and reception.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN009",
        "node_name": "Propaganda, wartime graphics, public information, state design",
        "date_start": "1914",
        "date_end": "1959",
        "date_text": "c.1914-1950s",
        "geo_centers": "Europe; USSR; U.S.; colonial administrations; anti-fascist networks",
        "transnational_routes": "State, military, colonial, and opposition information networks",
        "associated_formations": "War posters; public information; state exhibitions; political communication",
        "key_media_technologies": "Offset; lithography; photography; infographics",
        "key_object_types": "Posters; pamphlets; maps; manuals; public campaigns",
        "key_people": "",
        "key_institutions": "Government printing offices; ministries; war information offices",
        "likely_source_types": "National archives; poster collections; newspaper archives",
        "search_keywords": "propaganda; public information; war poster; ministry; bond drive",
        "required_metadata_fields": "issuing_body; campaign; locale; audience; language; rights_holder",
        "rights_risk_level": "Variable",
        "underdocumented_notes": "Anti-colonial, labor, and opposition graphics need equal treatment alongside state material.",
        "editorial_note": "Use issuing body and campaign metadata carefully.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN010",
        "node_name": "Swiss Style, grids, systems, information design, wayfinding",
        "date_start": "1945",
        "date_end": "1975",
        "date_text": "c.1945-1975",
        "geo_centers": "Zurich; Basel; Ulm; Milan; New York; Tokyo",
        "transnational_routes": "Design education, transit authorities, corporate and civic systems",
        "associated_formations": "International Typographic Style; systems design; information design",
        "key_media_technologies": "Grid systems; sans type; photographic reproduction; signage systems",
        "key_object_types": "Posters; identity manuals; transit graphics; maps; manuals",
        "key_people": "Josef Muller-Brockmann; Otl Aicher",
        "key_institutions": "Basel School; Ulm; transit authorities",
        "likely_source_types": "Design archives; museum collections; transit archives",
        "search_keywords": "swiss style; international typographic style; grid; wayfinding; pictogram",
        "required_metadata_fields": "system_name; client; implementation_site; component_type; version",
        "rights_risk_level": "Medium",
        "underdocumented_notes": "Non-Swiss systems in Japan, Latin America, India, and socialist states should be indexed comparatively.",
        "editorial_note": "Do not collapse systems design into Swiss canon only.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN011",
        "node_name": "Corporate identity, editorial systems, packaging systems",
        "date_start": "1950",
        "date_end": "1999",
        "date_text": "c.1950s-1990s",
        "geo_centers": "U.S.; Western Europe; Japan",
        "transnational_routes": "Multinational corporate routes",
        "associated_formations": "Corporate identity; branding; design management; editorial design",
        "key_media_technologies": "Offset lithography; phototypesetting; standards manuals",
        "key_object_types": "Logos; stationery; annual reports; manuals; packaging families; magazines",
        "key_people": "Unimark; Vignelli; Rand; Bass; Chermayeff & Geismar",
        "key_institutions": "Design consultancies; company archives; design centers",
        "likely_source_types": "Company archives; design centers; museum collections; trade press",
        "search_keywords": "corporate identity; standards manual; annual report; packaging system",
        "required_metadata_fields": "client; program; launch_date; sector; manual; component; implementation",
        "rights_risk_level": "High",
        "underdocumented_notes": "Many manuals survive privately or in incomplete scans; corporate ownership complicates image reuse.",
        "editorial_note": "Prefer link-only and metadata-first indexing.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN012",
        "node_name": "Protest graphics and counterpublics",
        "date_start": "1960",
        "date_end": "",
        "date_text": "c.1960s-present",
        "geo_centers": "Global",
        "transnational_routes": "Civil-rights; feminist; queer; labor; anti-colonial; anti-war routes",
        "associated_formations": "Protest poster workshops; feminist graphics; queer graphics; Black graphic histories; Indigenous and decolonial graphics",
        "key_media_technologies": "Screen print; photocopy; mimeograph; offset; digital print",
        "key_object_types": "Posters; flyers; buttons; zines; banners; newsletters",
        "key_people": "",
        "key_institutions": "Community printshops; activist collectives; Interference Archive; CSPG; QZAP; ONE; PGDA",
        "likely_source_types": "Community archives; poster archives; oral histories; web archives",
        "search_keywords": "protest poster; feminist graphics; queer zine; solidarity poster; labor graphics",
        "required_metadata_fields": "movement; campaign; collective; event; slogan; language; location",
        "rights_risk_level": "High",
        "underdocumented_notes": "Fragmented, anonymously authored, multilingual, and rights-sensitive.",
        "editorial_note": "Launch scope needs explicit counter-canon representation but cautious rights handling.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN013",
        "node_name": "Postmodern, vernacular, punk, zines, independent publishing",
        "date_start": "1970",
        "date_end": "2009",
        "date_text": "c.1970s-2000s",
        "geo_centers": "U.S.; UK; Europe; Japan; Latin America",
        "transnational_routes": "Global indie circuits",
        "associated_formations": "Postmodernism; punk; DIY; vernacular modernisms",
        "key_media_technologies": "Photocopy; paste-up; offset; collage; dry transfer",
        "key_object_types": "Zines; indie magazines; flyers; record sleeves; artist books",
        "key_people": "",
        "key_institutions": "Independent publishers; art schools; subcultural networks",
        "likely_source_types": "Zine archives; community archives; music archives; web documentation",
        "search_keywords": "postmodern graphic design; punk flyer; zine; vernacular design",
        "required_metadata_fields": "publication_type; scene; venue; contributor; distribution_mode",
        "rights_risk_level": "High",
        "underdocumented_notes": "Scene-based archives often preserve context poorly unless event, venue, and network fields are added.",
        "editorial_note": "Treat scene, venue, and distribution as first-class metadata.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN014",
        "node_name": "Phototypesetting, dry transfer, DTP, digital type",
        "date_start": "1960",
        "date_end": "2009",
        "date_text": "c.1960s-2000s",
        "geo_centers": "Europe; U.S.; Japan",
        "transnational_routes": "Global desktop-software routes",
        "associated_formations": "Technical modernization; independent type foundries",
        "key_media_technologies": "Phototypesetting; Letraset; paste-up; PostScript; digital fonts",
        "key_object_types": "Mechanicals; type specimens; ads; software packaging; font files",
        "key_people": "",
        "key_institutions": "Foundries; software firms; magazines; service bureaus",
        "likely_source_types": "Type archives; software collections; design archives; trade journals",
        "search_keywords": "phototypesetting; Letraset; paste-up; PostScript; font; specimen",
        "required_metadata_fields": "software; file_format; foundry; font_name; version; release_date",
        "rights_risk_level": "High",
        "underdocumented_notes": "Surviving production files are uneven; born-digital provenance can be fragile.",
        "editorial_note": "Do not ingest font binaries without permission.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
    {
        "node_id": "HN015",
        "node_name": "Web, interface, platform, algorithmic and generative communication",
        "date_start": "1990",
        "date_end": "",
        "date_text": "c.1990s-present",
        "geo_centers": "Global networked media",
        "transnational_routes": "Browser, platform, and template ecosystems",
        "associated_formations": "Web design; interface design; browser culture; social templates; platform aesthetics; generative and AI-assisted design",
        "key_media_technologies": "HTML/CSS; GUI assets; responsive systems; templates; motion graphics",
        "key_object_types": "Websites; apps; UI systems; design systems; social posts; motion templates",
        "key_people": "",
        "key_institutions": "Studios; platforms; browser teams; open-source communities",
        "likely_source_types": "Web archives; source repositories; screenshot sets; design-system docs",
        "search_keywords": "website; interface; ui kit; browser; social template; algorithmic feed; generative system",
        "required_metadata_fields": "url; capture_date; platform; version; viewport; file_hash; creator; model_used",
        "rights_risk_level": "Very high",
        "underdocumented_notes": "Capture must include time, version, viewport, and platform state; rights and privacy risks are significant.",
        "editorial_note": "Primarily link/capture metadata, not local reproduction.",
        "source_basis_note": "Rights-Aware Archive Index Framework report, historical node map.",
    },
]


movements_fields = [
    "movement_id",
    "name",
    "alternate_names",
    "date_start",
    "date_end",
    "date_text",
    "region",
    "group_type",
    "associated_people",
    "associated_institutions",
    "representative_media",
    "relation_to_graphic_design",
    "source_confidence",
    "search_terms",
    "authority_scheme",
    "authority_id",
    "authority_status",
    "editorial_scope_note",
]

movement_seed = [
    ("Arts and Crafts", "", "1860", "1919", "c.1860s-1910s", "UK; U.S.", "movement", "William Morris circles", "Kelmscott", "books; ornaments; interiors graphics", "reform foundation for modern design", "High", "arts and crafts; morris; kelmscott; reform book design", "Getty AAT; LC SH"),
    ("Art Nouveau", "Jugendstil; Modern Style; Sezessionstil", "1880", "1914", "c.1880s-1914", "France; Belgium; Austria; Germany; UK", "movement", "Horta; van de Velde; Secession circles", "", "posters; illustration; books", "core precursor to modern graphics", "High", "art nouveau; jugendstil; secession; affiche", "Getty AAT; LC SH"),
    ("Vienna Secession", "Sezession", "1897", "1918", "1897-1918", "Austria", "movement", "", "Secession; Ver Sacrum", "journals; exhibition graphics", "central to integrated modern design", "High", "vienna secession; ver sacrum", "LC; Getty"),
    ("Glasgow Style", "", "1890", "1919", "c.1890s-1910s", "Scotland", "regional formation", "Mackintosh; Macdonald", "", "posters; interiors; books", "reform-era graphics and display", "Medium", "glasgow style; mackintosh graphics", "Getty; LC"),
    ("Futurism", "Italian Futurism", "1909", "1939", "1909-1930s", "Italy; diaspora", "movement", "Marinetti network", "", "manifestos; books; typography", "experimental page and type", "High", "futurism typography; parolibere", "Getty AAT; LC"),
    ("Dada", "Zurich Dada; Berlin Dada", "1916", "1929", "1916-1920s", "Switzerland; Germany; France", "movement", "Tzara; Heartfield; Hoch", "", "collage; magazines; posters", "anti-rational graphic disruption", "High", "dada poster; dada magazine; photomontage", "Getty AAT; LC"),
    ("De Stijl", "Neo-Plasticism", "1917", "1931", "1917-1931", "Netherlands", "movement", "Doesburg; Mondrian", "", "journals; typography; architecture graphics", "abstract systems and layout", "High", "de stijl typography; doesburg", "Getty AAT; LC"),
    ("Constructivism", "Russian Constructivism", "1919", "1939", "1919-1930s", "USSR", "movement", "Rodchenko; Stepanova; Stenberg", "", "posters; books; agitprop", "major poster and publication formation", "High", "constructivist poster; rodchenko; stenberg", "Getty AAT; LC"),
    ("Suprematism", "", "1915", "1939", "c.1915-1930s", "Russia/USSR", "movement", "Malevich; Lissitzky links", "", "books; exhibitions", "abstract language feeding later graphics", "High", "suprematism; lissitzky design", "Getty AAT; LC"),
    ("Productivism", "Productivist design", "1920", "1929", "1920s", "USSR", "formation", "", "LEF; production art circles", "publications; utilitarian graphics", "links art to industrial/social production", "Medium", "productivism; LEF graphic design", "LC; editorial term"),
    ("Bauhaus", "Staatliches Bauhaus", "1919", "1933", "1919-1933", "Germany", "school", "Gropius; Moholy-Nagy; Bayer", "Bauhaus", "posters; teaching materials; stationery", "central design-school formation", "High", "bauhaus typography; bayer; moholy", "LCNAF; VIAF; ULAN"),
    ("New Typography", "Die Neue Typographie", "1920", "1939", "1920s-1930s", "Central Europe", "typography movement", "Jan Tschichold; avant-garde printers", "", "books; journals; ads", "core modern typographic regime", "High", "new typography; tschichold", "Getty; LC"),
    ("Nieuwe Zakelijkheid", "New Objectivity linked print cultures", "1920", "1939", "1920s-1930s", "Germany; Netherlands", "formation", "printers; commercial studios", "", "advertising; print ephemera", "modern commercial print formation", "Medium", "neue sachlichkeit graphic design", "LC; editorial term"),
    ("International Typographic Style", "Swiss Style", "1945", "1975", "c.1945-1975", "Switzerland; international", "movement", "Basel; Zurich; Muller-Brockmann", "", "posters; manuals; editorial design", "canonical grid/system formation", "High", "swiss style; grid system; basel school", "Getty; LC"),
    ("Ulm School", "HfG Ulm", "1953", "1968", "1953-1968", "Germany", "school", "Otl Aicher", "HfG Ulm", "identity systems; information graphics", "postwar systems design", "High", "hfg ulm; aicher; ulm design", "LCNAF; VIAF"),
    ("Corporate identity modernism", "systems design", "1950", "1989", "c.1950s-1980s", "U.S.; Europe; Japan", "technical/institutional formation", "Unimark; Vignelli; Rand", "", "identity manuals; signage", "central applied formation", "High", "corporate identity manual; standards program", "editorial term; firm authorities"),
    ("Editorial modernism", "", "1940", "1979", "c.1940s-1970s", "U.S.; Europe; Japan", "publishing formation", "", "magazines; newspaper redesign programs", "magazine systems; newspapers", "key publication design regime", "Medium", "editorial design modernist; magazine system", "editorial term"),
    ("Information design", "wayfinding; information graphics", "1940", "", "c.1940s-present", "global", "field", "transit authorities; designers; civic institutions", "", "maps; symbols; schedules", "major systems and public-design field", "High", "information design; wayfinding; pictogram", "Getty AAT; LC"),
    ("Photomontage politics", "montage graphics", "1920", "", "1920s-present", "Europe; USSR; global", "technique/formation", "Heartfield; activist designers", "", "posters; magazines", "recurring political graphics technique", "High", "photomontage poster; montage politics", "Getty AAT"),
    ("Wartime public information", "state propaganda; information services", "1914", "1959", "1914-1950s", "global", "state communication formation", "", "ministries; war offices; public agencies", "posters; pamphlets; maps", "mass persuasion graphics", "High", "war poster; public information poster", "editorial term; issuing body authority"),
    ("Poster workshop movements", "atelier; print collectives", "1960", "", "1960s-present", "Europe; Latin America; U.S.; Australia", "collective formation", "Atelier Populaire; community workshops", "", "screenprints; posters", "protest and solidarity graphics", "Medium", "poster workshop; serigraph poster collective", "editorial term"),
    ("Feminist graphics", "women's liberation graphics", "1960", "", "1960s-present", "global", "counterpublic formation", "women's presses; feminist collectives", "", "posters; newsletters; zines", "counterpublic design history", "Medium", "feminist poster; women's liberation graphic", "editorial term"),
    ("Queer graphics", "LGBTQ+ graphics", "1960", "", "1960s-present", "global", "counterpublic formation", "", "ONE; QZAP; community presses", "zines; posters; event graphics", "counterpublic design history", "Medium", "queer zine; pride poster; gay liberation graphics", "editorial term"),
    ("Black graphic histories", "African diasporic design histories", "1800", "", "19th c.-present", "U.S.; Caribbean; Africa; diaspora", "counter-canonical formation", "Black presses; printers; studios", "", "newspapers; posters; flyers", "essential canon corrective", "Medium", "Black press design; Black poster history", "editorial term"),
    ("Indigenous and decolonial graphics", "First Nations graphics", "1900", "", "20th c.-present", "global", "counter-canonical formation", "community publishers; Indigenous studios", "", "posters; bilingual print; campaigns", "sovereign and decolonial visual communication", "Medium", "Indigenous poster; decolonial graphic design", "editorial term"),
    ("Labor graphics", "union graphics; workers' press", "1800", "", "19th c.-present", "global", "movement communication", "", "unions; labor presses", "newspapers; buttons; banners", "activist and movement design", "Medium", "labor poster; union newspaper design", "LC subjects; editorial tag"),
    ("Punk graphics", "DIY punk; hardcore graphics", "1970", "", "1970s-present", "UK; U.S.; global", "subcultural formation", "labels; venues; bands; fanzines", "", "flyers; sleeves; zines", "subcultural graphic formation", "High", "punk flyer; punk zine; record sleeve", "editorial term"),
    ("Zine culture", "DIY publishing", "1970", "", "1970s-present", "global", "publishing culture", "", "QZAP; community archives", "zines; mini-comics; pamphlets", "independent publishing ecology", "High", "zine; minicomic; diy publishing", "Getty AAT; LC"),
    ("Postmodern graphic design", "New Wave; postmodern typography", "1970", "1999", "c.1970s-1990s", "U.S.; Europe", "movement", "Cranbrook-linked discourse; studios", "", "posters; books; magazines", "anti-universalist graphic formation", "High", "postmodern graphic design; new wave typography", "Getty; LC"),
    ("Vernacular design", "commercial vernacular; everyday graphics", "", "", "long duration", "global", "descriptor", "anonymous makers; local printers", "", "signs; wrappers; packaging; tickets", "anti-canonical descriptor", "Medium", "vernacular graphics; job printing; roadside sign", "Getty AAT; editorial term"),
    ("Dry-transfer and paste-up culture", "mechanical artwork era", "1960", "1989", "c.1960s-1980s", "global", "technical regime", "studios; service bureaus", "", "comps; boards; ad mechanicals", "technical regime affecting form", "High", "letraset; paste-up; mechanical art", "editorial term"),
    ("Desktop publishing", "DTP", "1984", "2009", "c.1984-2000s", "global", "technical regime", "Apple; Adobe; service bureaus", "", "brochures; newsletters; fonts", "digital production regime", "High", "desktop publishing; page layout software", "editorial term; software authority"),
    ("Independent digital type", "digital foundries", "1985", "", "c.1985-present", "global", "typographic formation", "foundries; type designers", "", "digital fonts; specimens; websites", "major field within design history", "High", "digital type foundry; specimen PDF", "editorial term; foundry/person authority"),
    ("Web design", "browser-era web", "1993", "2019", "c.1993-2010s", "global", "digital formation", "studios; browser teams", "", "websites; icons; style guides", "major born-digital formation", "High", "web design; browser culture; website graphic design", "editorial term"),
    ("Interface design", "UI; interaction design", "1980", "", "c.1980s-present", "global", "digital formation", "software firms; product teams", "", "GUIs; apps; systems", "graphic design expanded to interfaces", "High", "interface design; ui system; screen typography", "editorial term"),
    ("Social platform aesthetics", "template culture; feed graphics", "2010", "", "c.2010s-present", "global", "platform formation", "platforms; creators; agencies", "", "story graphics; social posts", "platformized visual communication", "High", "social media graphic; template pack; instagram design", "editorial term"),
    ("Generative design", "algorithmic graphics", "1960", "", "c.1960s experiments; 2010s-present mainstream", "global", "technical formation", "code artists; studios; toolmakers", "", "dynamic systems; outputs; templates", "procedural visual systems", "Medium", "generative design; algorithmic poster", "editorial term"),
    ("AI-assisted visual production", "diffusion-era graphics", "2022", "", "c.2022-present", "global", "technical formation", "tool platforms; mixed-author teams", "", "campaign mockups; composites; motion assets", "must be indexed as production context, not evidence", "Medium", "ai-assisted design; synthetic image workflow", "editorial term"),
]

movements = [
    {
        "movement_id": f"MV{i:03d}",
        "name": row[0],
        "alternate_names": row[1],
        "date_start": row[2],
        "date_end": row[3],
        "date_text": row[4],
        "region": row[5],
        "group_type": row[6],
        "associated_people": row[7],
        "associated_institutions": row[8],
        "representative_media": row[9],
        "relation_to_graphic_design": row[10],
        "source_confidence": row[11],
        "search_terms": row[12],
        "authority_scheme": row[13],
        "authority_id": "",
        "authority_status": "needs_resolution",
        "editorial_scope_note": "Seeded from Deep Research report; verify authority and scope before production ingest.",
    }
    for i, row in enumerate(movement_seed, 1)
]


media_fields = [
    "media_id",
    "term",
    "term_type",
    "definition",
    "date_start",
    "date_end",
    "date_text",
    "relation_to_graphic_design",
    "associated_source_types",
    "required_metadata_fields",
    "search_keywords",
    "rights_display_issues",
    "authority_scheme",
    "authority_id",
]

media_seed = [
    ("Letterpress", "process", "Relief printing from raised type/forms", "1450", "", "1450s-20th c.; revival later", "core typographic production regime", "rare books; job-print archives; type archives", "process; press; typeface; printer; edition", "letterpress; handset; relief print", "usually safe for older objects; revival work often copyrighted"),
    ("Woodcut", "process", "Relief image cut on wood block", "", "", "long duration", "illustration and broadside precursor", "print rooms; rare books", "block maker; edition; state", "woodcut; block print", "older works often low-risk"),
    ("Engraving", "process", "Incised metal-plate intaglio", "1500", "1899", "16th-19th c.", "illustration, maps, trade ephemera", "print collections; maps", "process; plate; engraver; publisher", "engraving; steel engraving", "older works low-risk"),
    ("Etching", "process", "Acid-bitten metal intaglio", "1500", "", "16th c.-present", "illustration and art/print crossover", "print rooms; artist-book archives", "process; state; plate", "etching", "modern images may remain copyrighted"),
    ("Lithography", "process", "Planographic process from stone/plate", "1796", "", "1796-present", "foundational for poster and commercial print", "poster archives; museum APIs", "process; printer; colors", "lithograph; poster print", "19th-c. often low-risk; later posters high-risk"),
    ("Chromolithography", "process", "Multi-stone color lithography", "1800", "1930", "19th c.-early 20th c.", "labels, trade cards, packaging, posters", "ephemera collections", "color count; process; printer", "chromolithograph; label; trade card", "often older, but scans may have provider restrictions"),
    ("Screen printing", "process", "Ink forced through stencil mesh", "1900", "", "20th c.-present", "protest graphics, posters, DIY print", "poster/community archives", "process; workshop; edition", "screenprint; serigraph", "many modern posters still copyrighted"),
    ("Offset lithography", "process", "Industrial commercial print process", "1900", "", "20th c.-present", "magazines, books, packaging, corporate print", "periodicals; annual reports", "process; print run; printer", "offset; offset litho", "high rights risk for modern works"),
    ("Halftone", "process", "Reproduction of tonal images via dots", "1880", "", "late 19th c.-present", "newspaper/magazine image reproduction", "newspaper and periodical archives", "screen; reproduction method", "halftone; photoengraving", "page images may be usable only if public domain"),
    ("Photomontage", "technique", "Composite image assembly", "1900", "", "20th c.-present", "major avant-garde and political technique", "magazines; posters; books", "technique; source_images; documented_relation", "photomontage; montage", "attribution may be complex"),
    ("Phototypesetting", "technology", "Type generated photographically", "1950", "1989", "1950s-1980s", "transition from metal to digital layout", "trade journals; studio archives", "system_name; manufacturer", "phototypesetting; cold type", "artifacts and manuals often under copyright"),
    ("Dry transfer", "technology/material", "Rub-down transfer lettering", "1960", "1999", "1960s-1990s", "paste-up-era design labor", "studio archives; product ephemera", "brand; sheet; size", "dry transfer; Letraset", "product imagery and scans may be restricted"),
    ("Letraset", "brand/system", "Dry-transfer brand/system", "1960", "1999", "1960s-1990s", "material culture of layout and comps", "type archives; private collections", "brand; set number; font", "Letraset", "trademark and scan reuse issues"),
    ("Paste-up", "production method", "Manual page assembly", "1900", "1999", "20th c.", "production method for editorial and advertising", "studio archives; mechanicals", "board size; overlays; proofs", "paste-up; mechanical art", "often unique working documents"),
    ("Mechanical artwork", "production artifact", "Camera-ready production art", "1900", "1999", "20th c.", "key prepress artifact", "studio archives", "proof stage; crop marks; instructions", "mechanical; comp; stat", "often unpublished and high-risk"),
    ("Type specimen", "format", "Sample publication for typefaces", "1500", "", "16th c.-present", "central evidence for type history", "type archives; libraries", "foundry; font; issue_date", "type specimen; foundry specimen", "older specimens low-risk; recent PDFs high-risk"),
    ("Magazine", "format", "Serial periodical issue", "1700", "", "18th c.-present", "editorial systems, art direction, typography", "periodical archives", "title; issue; volume; date; page span", "magazine; periodical; issue", "issue-level rights vary strongly"),
    ("Newspaper", "format", "Serial news publication", "1600", "", "17th c.-present", "grids, public communication, ads", "newspaper archives", "title; issue_date; edition; page", "newspaper; daily; gazette", "public-domain status depends on date/jurisdiction"),
    ("Poster", "format", "Single-sheet public print", "1800", "", "19th c.-present", "canonical graphic design object", "poster archives; museum collections", "dimensions; edition; venue; event", "poster; affiche; placard", "often high-risk after 20th c."),
    ("Book jacket", "format", "Printed book wrapper", "1890", "", "late 19th c.-present", "publishing and retail graphics", "library jackets; publisher archives", "book_id; jacket_designer; edition", "dust jacket; book jacket", "modern jackets usually copyrighted"),
    ("Exhibition catalogue", "format", "Exhibition publication", "1800", "", "19th c.-present", "exhibition graphics and canon formation", "museum libraries; IA; HathiTrust", "exhibition; venue; dates; ISBN", "exhibition catalogue", "often text rights and image rights mixed"),
    ("Corporate identity manual", "format", "Standards document for identity program", "1950", "", "1950s-present", "primary evidence for systems design", "company archives; design archives", "client; version; section", "identity manual; standards manual", "typically high-risk; link-only safest"),
    ("Packaging", "format/object type", "Container / wrapper graphics", "", "", "long duration", "branding and commodity culture", "museum collections; trade ephemera", "product; brand; material; market", "packaging; wrapper; carton; label", "trademarks and trade dress complicate reuse"),
    ("Signage", "format/system", "Environmental sign object/system", "1900", "", "20th c.-present", "public visual communication", "museum collections; transit archives", "site; system; component", "sign; signage system", "modern public-sign imagery may be fine; manuals less so"),
    ("Wayfinding", "system", "Navigational graphic system", "1900", "", "20th c.-present", "systems and information design", "transit/civic archives", "site; phase; pictogram set", "wayfinding; orientation system", "usually high-risk if manual drawings reused"),
    ("Map", "format", "Spatial graphic representation", "", "", "long duration", "information design and public communication", "libraries; government archives", "scale; projection; place", "map; transit map; route map", "rights vary by date and jurisdiction"),
    ("Information graphic", "format", "Diagram/chart/visual explanation", "1800", "", "19th c.-present", "data visualization lineage", "magazines; books; public agencies", "data_source; chart_type", "infographic; chart; diagram", "often embedded within copyrighted page layouts"),
    ("Zine", "format", "Small-circulation DIY publication", "1900", "", "20th c.-present", "subculture and counterpublic print", "QZAP; community archives", "issue; collective; scene; copier", "zine; fanzine; minicomic", "high rights/privacy sensitivity"),
    ("Website", "format", "Networked page/site", "1990", "", "1990s-present", "core born-digital design format", "web archives", "url; capture_date; platform", "website; homepage; microsite", "copyright, privacy, scripts, dynamic capture issues"),
    ("Interface", "format/system", "Screen-based user interface", "1980", "", "1980s-present", "graphic design in software context", "design-system docs; screenshots", "version; viewport; OS; state", "interface; ui; screen", "screenshots may implicate software trademarks/IP"),
    ("Digital font", "software/format", "Font software file and release", "1980", "", "1980s-present", "central to digital typography", "foundry sites; type archives", "font_name; version; format; foundry", "otf; ttf; variable font", "fonts are licensed software; never ingest binaries without permission"),
    ("Template", "format", "Reusable layout or asset package", "2000", "", "2000s-present", "platformized design labor", "marketplaces; brand systems", "template_name; platform; dimensions", "template; pack; social template", "usually not safe to copy; metadata-only"),
    ("Social media graphic", "format", "Post/story/feed asset", "2010", "", "2010s-present", "platform-native visual communication", "web/social archives", "platform; post_date; aspect_ratio", "post graphic; story graphic", "high risk; often link/screenshot only with context"),
    ("Motion graphic", "format", "Animated visual communication asset", "1980", "", "late 20th c.-present", "extension of graphic design into time", "video archives; studio reels", "duration; codec; soundtrack", "motion graphic; title sequence", "rights often layered and complex"),
    ("Generative visual system", "system", "Rule-based or code-based visual output", "1960", "", "1960s experiments; current mainstream", "procedural design and adaptive systems", "repositories; exhibitions", "algorithm; seed; runtime; output_type", "generative system; algorithmic poster", "document code, model, prompt, version; do not treat outputs as self-authenticating evidence"),
]

media_technologies = [
    {
        "media_id": f"MT{i:03d}",
        "term": row[0],
        "term_type": row[1],
        "definition": row[2],
        "date_start": row[3],
        "date_end": row[4],
        "date_text": row[5],
        "relation_to_graphic_design": row[6],
        "associated_source_types": row[7],
        "required_metadata_fields": row[8],
        "search_keywords": row[9],
        "rights_display_issues": row[10],
        "authority_scheme": "",
        "authority_id": "",
    }
    for i, row in enumerate(media_seed, 1)
]


source_fields = [
    "source_id",
    "name",
    "url",
    "source_type",
    "access_method",
    "api_base_or_endpoint",
    "iiif_support",
    "oai_pmh_support",
    "dataset_support",
    "geo_coverage",
    "historical_coverage",
    "graphic_design_relevance",
    "likely_record_types",
    "rights_summary",
    "rights_uri_support",
    "metadata_quality_estimate",
    "stable_identifiers",
    "automated_ingestion",
    "link_only_safer",
    "priority",
    "notes",
    "last_verified_date",
]

source_seed = [
    ("The Met Open Access", "https://www.metmuseum.org/hubs/open-access", "museum collection", "API + CSV", "global", "broad historical span", "high for posters, prints, books, decorative arts", "objects; images", "API exposes CC0 Open Access images and data for designated public-domain records.", "yes", "High", "yes", "Yes", "No for OA records", "Launch", "Use only explicit Open Access records for images."),
    ("Cooper Hewitt API", "https://apidocs.cooperhewitt.org/", "design museum", "API + open data", "global", "30 centuries of design", "very high", "objects; people; tags", "Collection data excluding images released under CC0; images require separate care.", "partial", "High", "yes", "Yes", "Yes for images", "Launch", "Strong design-specific metadata source."),
    ("Smithsonian Open Access", "https://www.si.edu/openaccess", "museum/archive aggregate", "API + GitHub + search", "U.S.; global holdings", "broad", "high", "objects; media; 2D/3D assets", "CC0 for OA assets; non-CC0 items remain restricted.", "yes", "High", "yes", "Yes", "Mixed", "Launch", "Good for low-risk open image examples."),
    ("Rijksmuseum Data Services", "https://data.rijksmuseum.nl/", "museum + library + vocabularies", "Search API + OAI-PMH + IIIF + dumps + SRU", "Netherlands; Europe", "early modern-present", "very high for books, prints, posters, design context", "objects; library records; vocabularies", "Open data policy; restrictions signaled when applicable.", "yes", "Very high", "yes", "Yes", "No for openly licensed records", "Launch", "Excellent machine-readable source."),
    ("V&A Collections API", "https://developers.vam.ac.uk/guide/v2/", "museum collection", "API", "UK; global", "broad art/design/archives/library", "very high", "objects; images; archives metadata", "Collection data and images available; object-level rights vary.", "partial", "High", "yes", "Yes", "Yes for images", "Launch", "Keep image policy conservative."),
    ("Library of Congress loc.gov API", "https://www.loc.gov/apis/", "national library", "API + JSON/YAML + IIIF microservices", "U.S.; global", "broad", "very high for prints, posters, books, periodicals", "collection items; authorities; images; text", "Structured access; rights vary by collection.", "mixed", "High", "yes", "Yes", "Mixed", "Launch", "Pair with LoC rights notes."),
    ("Chronicling America", "https://www.loc.gov/collections/chronicling-america/", "newspaper archive", "loc.gov API + datasets + IIIF text/image services", "U.S.", "newspapers through 1963", "very high for advertising, editorial design, public graphics", "titles; pages; OCR text", "Materials public domain or no known restrictions, with caution for later third-party materials.", "mixed", "High", "yes", "Yes", "Often no", "Launch", "Useful for search/word frequency experiments."),
    ("Europeana API", "https://api.europeana.eu/", "cultural-heritage aggregator", "API", "Europe", "broad", "very high for cross-border discovery", "EDM records; previews; provider links", "API metadata CC0; linked objects follow their own rights statements.", "yes", "High", "yes", "Yes", "Yes for partner objects", "Launch", "Use as discovery layer, not image source by default."),
    ("DPLA", "https://dp.la/", "cultural-heritage aggregator", "API + MAP docs", "U.S.", "broad", "high for distributed discovery", "items; providers; views", "Source/web-resource separation; rights fields for source and preview objects.", "mixed", "High", "yes", "Yes", "Yes for linked objects", "Launch", "Good metadata model precedent."),
    ("Trove", "https://trove.nla.gov.au/", "national aggregator", "API + bulk download + search", "Australia", "broad; newspapers, magazines, web archive discovery", "very high", "records; newspaper full text; organizations; titles", "API key required; metadata/text available; archived websites excluded from API.", "mixed", "High", "yes", "Yes", "Mixed", "Launch", "Useful for Australian dimension."),
    ("DigitalNZ", "https://digitalnz.org/developers", "national aggregator", "API", "Aotearoa New Zealand", "broad", "high for distributed design ephemera", "metadata records; pointers; thumbnails", "Aggregates metadata and links/thumbnails to partner items; rights vary by partner.", "mixed", "High", "yes", "Yes", "Usually yes", "Launch", "Good aggregator pattern."),
    ("MoMA Collection", "https://www.moma.org/collection/", "museum collection", "search interface", "U.S.; international modern/contemporary", "modern-contemporary", "very high", "artworks; artists; classifications", "Rich metadata; rights vary strongly by work.", "partial", "High", "yes", "No", "Yes", "Launch", "Manual/link-first; do not scrape images."),
    ("Cary Graphic Design Archive", "https://www.rit.edu/carycollection/graphic-design-archive", "university special collection", "manual", "U.S.", "especially 1920s-1960s", "very high", "designer archives; posters; publications", "Research access; image copying manual-review only.", "unknown", "High", "yes", "No", "Yes", "Launch", "Design-history depth, link-first."),
    ("Vignelli Center for Design Studies", "https://www.rit.edu/vignellicenter/", "university design archive", "manual", "U.S.; international", "20th c.-present", "very high", "archives; identity systems; publication design", "Rich archival holdings; manual access route.", "unknown", "High", "yes", "No", "Yes", "Launch", "Important for corporate identity/systems."),
    ("Herb Lubalin Study Center", "https://cooper.edu/art/herb-lubalin-study-center-design-and-typography", "university design archive", "manual + Flat File", "U.S.", "20th c.", "very high", "ephemera; archives; library resources", "Preservation/research mission; link-only unless permission.", "unknown", "High", "yes", "No", "Yes", "Launch", "Strong typography/editorial anchor."),
    ("People's Graphic Design Archive", "https://peoplesgdarchive.org/", "crowdsourced design archive", "search interface", "global/community", "broad modern-contemporary", "very high", "uploads; links; oral histories; essays; images", "Rights remain with rights holders.", "mixed", "Medium", "yes", "No", "Yes", "Launch", "Inclusive/community source; manual review."),
    ("Interference Archive", "https://interferencearchive.org/", "community archive", "digital catalog + manual", "U.S.; global movements", "social movement cultural production", "very high for protest graphics", "posters; flyers; zines; books; buttons; AV", "Rights and sensitivity review required.", "mixed", "Medium", "yes", "No", "Yes", "Launch", "Counterpublic/protest anchor."),
    ("Center for the Study of Political Graphics", "https://www.politicalgraphics.org/collection", "political poster archive", "online catalog + manual", "global", "20th c.-present", "very high", "poster records; images", "Searchable records; catalog in progress; images rights-sensitive.", "partial", "Medium-high", "yes", "Partial", "Yes for images", "Launch", "Political poster anchor."),
    ("PANDORA / Australian Web Archive", "https://pandora.nla.gov.au/", "web archive", "search interface", "Australia", "online publications since 1996", "high for web/networked design history", "archived websites; online publications", "Use captured URLs/timestamps, not copied assets.", "mixed", "Medium", "yes", "No", "Yes", "Launch", "Born-digital capture context."),
    ("Art Institute of Chicago API", "https://api.artic.edu/", "museum collection", "API", "global", "broad", "high for posters, prints, publications", "objects; publications; digital publications", "API data may be protected; use cautiously.", "partial", "High", "yes", "Yes with caution", "Yes", "Launch", "Good publication/object data but rights caution."),
    ("Harvard Art Museums API", "https://harvardartmuseums.org/collections/api", "museum collection", "API", "global", "broad", "moderate-high", "objects; people; exhibitions", "Rights vary by object.", "partial", "High", "yes", "Yes", "Yes", "Launch", "Useful museum-linked records."),
    ("Cleveland Museum Open Access API", "https://openaccess-api.clevelandart.org/", "museum collection", "API + datasets", "global", "broad", "moderate", "objects; images", "Dataset and many images CC0; copyrighted works may still appear.", "yes", "High", "yes", "Yes", "Mixed", "Launch", "Lower-risk open access testing."),
    ("Gallica / BnF APIs", "https://api.bnf.fr/", "national library digital platform", "SRU/API/IIIF/datasets", "France", "books, periodicals, images, press", "very high", "documents; OCR; images; periodicals", "Rights/access vary; rate limits.", "mixed", "High", "yes", "Yes", "Mixed", "Launch", "French print and poster context."),
    ("HathiTrust", "https://www.hathitrust.org/member-libraries/resources-for-librarians/data-resources/", "digital library", "bibliographic API + data API + OAI + hathifiles", "partner libraries", "books/serials", "high for periodicals, catalogues, specimens", "bibliographic records; OCR; page images; OAI", "Access varies; APIs are not search APIs.", "mixed", "Medium-high", "yes", "Partial", "Often yes", "Launch", "Use bibliographic/OAI pathways."),
    ("Internet Archive", "https://archive.org/developers/", "digital library / web archive", "metadata API + search APIs + Wayback APIs", "global", "broad", "high but heterogeneous", "items; files; metadata; captures", "Rights vary widely by item and uploader.", "mixed", "Medium", "partial", "Partial", "Yes", "Launch", "Good discovery, high rights variability."),
    ("NDL Search", "https://ndlsearch.ndl.go.jp/en", "national library aggregator", "search interface + linked services", "Japan", "books, newspapers, maps, websites", "high for Japanese magazines, books, web sites", "books; newspapers; maps; websites; online publications", "Access varies by item and registration status.", "mixed", "High", "yes", "Partial", "Yes", "Launch", "Important for Japan coverage."),
    ("Type Archive", "https://www.typearchive.org/", "type and printing archive", "manual", "UK", "typefounding and printing", "very high", "typefounding artifacts; specimens; archives", "Archival collection; manual review needed.", "unknown", "Medium-high", "yes", "No", "Yes", "Launch", "Type history source."),
    ("St Bride Library / Foundation", "https://sbf.org.uk/library/", "printing and typographic library", "manual + digital collections", "UK", "history of print, typography, design", "very high", "books; serials; talks; archives", "Digital rights vary.", "unknown", "High", "yes", "No", "Yes", "Launch", "Major typography library."),
    ("Fonts In Use", "https://fontsinuse.com/", "typography database", "search interface", "global", "contemporary and historical uses", "high", "uses; typefaces; formats; topics", "Rights mixed and example-specific.", "mixed", "Medium", "yes", "No", "Yes", "Launch", "Type-in-use relation source."),
    ("Library of Congress Web Archives", "https://www.loc.gov/web-archives/collections/", "web archive", "search interface", "U.S.; global topics", "born-digital", "high for born-digital context", "archived sites; collections", "Link/citation first.", "mixed", "Medium", "yes", "No", "Yes", "Launch", "Born-digital source."),
    ("Archive-It", "https://www.archive-it.org/", "web archiving platform", "Partner API + CDX/C + OAI", "global partner archives", "born-digital", "high for design websites if partner-collected", "collections; crawls; captures", "Richer access partner-oriented; link/capture metadata safest.", "mixed", "Medium", "partial", "Partial", "Yes", "Launch", "Web archive infrastructure."),
    ("Asia Art Archive", "https://aaa.org.hk/en/collections/search", "regional art archive", "search interface", "Asia", "recent art and publishing contexts", "moderate-high", "archival materials; library materials; projects", "Manual review advised.", "unknown", "Medium", "yes", "No", "Yes", "Launch", "Regional context beyond Euro-American canon."),
    ("ONE Archives", "https://one.usc.edu/", "community archive", "search interface", "U.S.; LGBTQ+", "20th c.-present", "high for queer periodicals, posters, ephemera", "archives; exhibitions; records", "Rights vary; link-only safest without permission.", "unknown", "Medium", "yes", "No", "Yes", "Launch", "Queer history source."),
    ("SAADA", "https://www.saada.org/explore/archive", "community digital archive", "search interface", "South Asian American", "modern-contemporary", "moderate-high for diasporic print and visual culture", "archive items; topics; collections", "Community-focused stewardship; manual review.", "mixed", "Medium", "yes", "No", "Yes", "Launch", "Diasporic/community source."),
    ("QZAP", "https://gittings.qzap.org/", "queer zine archive", "search interface", "global/queer community", "modern-contemporary", "high for zine culture", "zines; scans; metadata", "Volunteer archive; use citations and links, not bulk copies.", "mixed", "Medium", "yes", "No", "Yes", "Launch", "Zine/counterpublic source."),
]

source_registry = [
    {
        "source_id": f"SRC{i:03d}",
        "name": row[0],
        "url": row[1],
        "source_type": row[2],
        "access_method": row[3],
        "api_base_or_endpoint": row[1],
        "iiif_support": "unknown",
        "oai_pmh_support": "unknown",
        "dataset_support": "unknown",
        "geo_coverage": row[4],
        "historical_coverage": row[5],
        "graphic_design_relevance": row[6],
        "likely_record_types": row[7],
        "rights_summary": row[8],
        "rights_uri_support": row[9],
        "metadata_quality_estimate": row[10],
        "stable_identifiers": row[11],
        "automated_ingestion": row[12],
        "link_only_safer": row[13],
        "priority": "Launch",
        "notes": row[15],
        "last_verified_date": "2026-05-29",
    }
    for i, row in enumerate(source_seed, 1)
]


search_vocabulary_fields = [
    "term_id",
    "term",
    "normalized_term",
    "term_class",
    "language",
    "alternate_forms",
    "broader_term",
    "narrower_term",
    "related_terms",
    "preferred_for_query",
    "query_context",
    "authority_scheme",
    "authority_id",
    "notes",
]

vocab_groups = {
    "movement": "arts and crafts; art nouveau; jugendstil; secession; bauhaus; new typography; swiss style; international typographic style; constructivism; suprematism; productivism; dada; futurism; de stijl; postmodern graphic design; punk graphics; feminist graphics; queer graphics; labor graphics; decolonial graphics",
    "medium_technology": "letterpress; lithograph; chromolithograph; screenprint; offset lithography; halftone; engraving; etching; woodcut; photomontage; phototypesetting; letraset; dry transfer; paste-up; mechanical artwork; postscript; digital font; variable font; html; css; ui; generative",
    "object_type": "poster; broadside; pamphlet; book; book jacket; dust jacket; magazine; periodical; newspaper; catalogue; exhibition catalogue; annual report; identity manual; packaging; label; wrapper; signage; map; chart; infographic; zine; website; interface; app screen; motion graphic",
    "institutional": "press; printer; publisher; foundry; studio; collective; ministry; transit authority; museum; archive; library; school; workshop; union; community press",
    "theme": "propaganda; public information; advertising; branding; editorial design; typography; wayfinding; pictogram; protest; solidarity; antiwar; women's liberation; gay liberation; anti-apartheid; civil rights; anti-colonial; labor",
    "regional": "central europe; basel; zurich; ulm; weimar; dessau; moscow; petrograd; milan; tokyo; mexico city; havana; warsaw; tehran; delhi; sao paulo; lagos; melbourne; auckland",
    "multilingual_hook": "affiche; plakat; revista; periodico; cartel; cartaz; tipografia; typographie; grafica; diseno grafico; affiches politiques; revista ilustrada; 新聞; 雑誌; ポスター",
    "museum_api_retrieval": "graphic design; illustrated book; periodical; poster; publication design; website; ephemera; work on paper; typography; trade card; label; wrapper; archive; collection; digital object",
    "newspaper_periodical_retrieval": "advertisement; ad; classified; supplement; masthead; headline; serial; issue; vol.; no.; illustrated; cover; special number; campaign; exhibition notice",
}

search_vocabulary = []
tid = 1
for klass, terms in vocab_groups.items():
    for term in [t.strip() for t in terms.split(";") if t.strip()]:
        search_vocabulary.append(
            {
                "term_id": f"SV{tid:04d}",
                "term": term,
                "normalized_term": term.lower(),
                "term_class": klass,
                "language": "und",
                "alternate_forms": "",
                "broader_term": "",
                "narrower_term": "",
                "related_terms": "",
                "preferred_for_query": "yes",
                "query_context": "deterministic search seed from report",
                "authority_scheme": "",
                "authority_id": "",
                "notes": "Seed term; authority and multilingual expansion pending.",
            }
        )
        tid += 1


rights_fields = [
    "strategy_id",
    "source_category",
    "rights_signal",
    "ingest_policy",
    "display_policy",
    "review_required",
    "citation_required",
    "attrib_required",
    "thumbnail_allowed",
    "full_image_allowed",
    "iiif_embed_allowed",
    "notes",
]

rights_strategy = [
    {
        "strategy_id": "RS001",
        "source_category": "Open-access museum APIs",
        "rights_signal": "CC0 / Public Domain Mark / explicit unrestricted OA",
        "ingest_policy": "metadata + image URL + derivative-safe flag",
        "display_policy": "full image allowed",
        "review_required": "no for flagged records",
        "citation_required": "yes",
        "attrib_required": "recommended",
        "thumbnail_allowed": "yes",
        "full_image_allowed": "yes",
        "iiif_embed_allowed": "yes if available",
        "notes": "Store rights URI and OA flag per record; do not infer openness for unflagged records.",
    },
    {
        "strategy_id": "RS002",
        "source_category": "Reuse-licensed records",
        "rights_signal": "CC BY / CC BY-SA / other explicit reuse license",
        "ingest_policy": "metadata + image URL + attribution fields",
        "display_policy": "full image allowed with required credit",
        "review_required": "yes for license compatibility",
        "citation_required": "yes",
        "attrib_required": "yes",
        "thumbnail_allowed": "yes",
        "full_image_allowed": "yes with license conditions",
        "iiif_embed_allowed": "yes if license travels with manifest",
        "notes": "Preserve license label, URI, attribution text, and source link.",
    },
    {
        "strategy_id": "RS003",
        "source_category": "RightsStatements.org NoC-* records",
        "rights_signal": "No known copyright / related RightsStatements.org URI",
        "ingest_policy": "metadata + source image URL",
        "display_policy": "full image only if statement permits and source terms align",
        "review_required": "yes",
        "citation_required": "yes",
        "attrib_required": "recommended",
        "thumbnail_allowed": "yes if source permits",
        "full_image_allowed": "conditional",
        "iiif_embed_allowed": "conditional",
        "notes": "RightsStatements.org labels help but do not replace provider terms.",
    },
    {
        "strategy_id": "RS004",
        "source_category": "Mixed-rights museum APIs",
        "rights_signal": "InC / InC-OW-EU / unknown / proprietary notice",
        "ingest_policy": "metadata + source link + optional thumbnail pointer",
        "display_policy": "no full image; manual review",
        "review_required": "yes",
        "citation_required": "yes",
        "attrib_required": "yes if displayed",
        "thumbnail_allowed": "conditional",
        "full_image_allowed": "no by default",
        "iiif_embed_allowed": "conditional",
        "notes": "Never infer image reuse from public record visibility.",
    },
    {
        "strategy_id": "RS005",
        "source_category": "Aggregators returning partner links",
        "rights_signal": "aggregator metadata plus provider rights field",
        "ingest_policy": "metadata only + provider link",
        "display_policy": "link to provider unless object-level rights verified",
        "review_required": "yes for media display",
        "citation_required": "yes",
        "attrib_required": "yes",
        "thumbnail_allowed": "conditional",
        "full_image_allowed": "no by default",
        "iiif_embed_allowed": "conditional",
        "notes": "Aggregator metadata may be open while partner objects are not.",
    },
    {
        "strategy_id": "RS006",
        "source_category": "IIIF endpoints",
        "rights_signal": "manifest rights / requiredStatement / provider fields",
        "ingest_policy": "manifest URL + metadata + rights fields",
        "display_policy": "IIIF/embed only unless reuse rights are clear",
        "review_required": "yes",
        "citation_required": "yes",
        "attrib_required": "yes",
        "thumbnail_allowed": "conditional",
        "full_image_allowed": "conditional",
        "iiif_embed_allowed": "yes if provider allows",
        "notes": "IIIF is a presentation layer, not a discovery substitute.",
    },
    {
        "strategy_id": "RS007",
        "source_category": "Community archives and crowdsourced archives",
        "rights_signal": "contributor/rights-holder complexity",
        "ingest_policy": "link only or metadata only",
        "display_policy": "manual review required for image reuse",
        "review_required": "yes",
        "citation_required": "yes",
        "attrib_required": "yes",
        "thumbnail_allowed": "no by default",
        "full_image_allowed": "no by default",
        "iiif_embed_allowed": "conditional",
        "notes": "Respect privacy, community protocols, and contributor rights.",
    },
    {
        "strategy_id": "RS008",
        "source_category": "Special collections without explicit licenses",
        "rights_signal": "no clear reuse license",
        "ingest_policy": "link only + holding/finding-aid metadata",
        "display_policy": "no image display without permission",
        "review_required": "yes",
        "citation_required": "yes",
        "attrib_required": "yes",
        "thumbnail_allowed": "no by default",
        "full_image_allowed": "no",
        "iiif_embed_allowed": "conditional",
        "notes": "Index holdings and reading-room info; request permissions case by case.",
    },
    {
        "strategy_id": "RS009",
        "source_category": "Social/web captures",
        "rights_signal": "archived URL / capture timestamp / platform terms",
        "ingest_policy": "URL + capture timestamp + archive source metadata",
        "display_policy": "link only unless archive provides lawful embed/thumbnail",
        "review_required": "yes",
        "citation_required": "yes",
        "attrib_required": "yes",
        "thumbnail_allowed": "conditional",
        "full_image_allowed": "no by default",
        "iiif_embed_allowed": "not typical",
        "notes": "Store viewport, version, and capture context where available.",
    },
    {
        "strategy_id": "RS010",
        "source_category": "Font software / downloadable digital assets",
        "rights_signal": "licensed product or software asset",
        "ingest_policy": "metadata only",
        "display_policy": "do not ingest binaries; link to source/specimen",
        "review_required": "yes",
        "citation_required": "yes",
        "attrib_required": "yes",
        "thumbnail_allowed": "conditional",
        "full_image_allowed": "no by default",
        "iiif_embed_allowed": "no",
        "notes": "Catalog names, foundries, versions, and specimens; never copy font binaries without permission.",
    },
]


def write_readme() -> None:
    readme = DATA / "README.md"
    readme.write_text(
        """# Seed Data v0

This directory contains the first structured seed files for the Modern Graphic Design History Archive Index.

Source basis: `Rights-Aware Archive Index Framework for Modern Graphic Design History.docx`, reviewed in the project folder on 2026-05-29.

Generated by: `scripts/generate_seed_data.py`

Files:

- `historical_nodes.csv`: initial historical spine and node map.
- `movements.csv`: movements, formations, schools, regimes, and counter-historical groupings.
- `media_technologies.csv`: media, processes, technologies, and formats.
- `source_registry.csv`: candidate source universe with access and rights notes.
- `search_vocabulary.csv`: deterministic search vocabulary seed.
- `rights_strategy.csv`: rights-safe indexing and display rules.

Status:

- These files are implementation seeds, not final scholarly authority.
- Authority IDs, jurisdiction-specific copyright review, and source-specific terms review remain pending.
- Images should not be ingested from these sources unless the relevant rights fields and source terms clearly allow it.
""",
        encoding="utf-8",
    )


def main() -> None:
    write_csv(DATA / "historical_nodes.csv", historical_nodes_fields, historical_nodes)
    write_csv(DATA / "movements.csv", movements_fields, movements)
    write_csv(DATA / "media_technologies.csv", media_fields, media_technologies)
    write_csv(DATA / "source_registry.csv", source_fields, source_registry)
    write_csv(DATA / "search_vocabulary.csv", search_vocabulary_fields, search_vocabulary)
    write_csv(DATA / "rights_strategy.csv", rights_fields, rights_strategy)
    write_readme()


if __name__ == "__main__":
    main()
