#!/usr/bin/env python3
"""Generate 1990-2026 contemporary/edge source candidates.

This file creates a source-level candidate registry only. It does not ingest item
records, images, or platform media. Impact/priority language is internal triage
only and must not be rendered as public authority.
"""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data" / "contemporary_source_scan_candidates_1990_2026_v1.csv"

FIELDNAMES = [
    "candidate_id",
    "source_name",
    "macro_region",
    "subregion",
    "country_or_region",
    "source_class",
    "institutional_level",
    "protocol_family",
    "url",
    "period_start",
    "period_end",
    "period_bands",
    "expected_record_types",
    "capture_route",
    "recommended_adapter",
    "recommended_image_policy",
    "text_enrichment_path",
    "rights_posture",
    "risk_notes",
    "priority",
    "inclusion_status",
    "notes",
]


def row(
    source_name: str,
    macro_region: str,
    subregion: str,
    country_or_region: str,
    source_class: str,
    institutional_level: str,
    protocol_family: str,
    url: str,
    period_start: str,
    period_end: str,
    period_bands: str,
    expected_record_types: str,
    capture_route: str,
    recommended_adapter: str,
    recommended_image_policy: str,
    text_enrichment_path: str,
    rights_posture: str,
    risk_notes: str,
    priority: str,
    inclusion_status: str = "candidate_probe",
    notes: str = "",
) -> dict[str, str]:
    return {
        "candidate_id": "",
        "source_name": source_name,
        "macro_region": macro_region,
        "subregion": subregion,
        "country_or_region": country_or_region,
        "source_class": source_class,
        "institutional_level": institutional_level,
        "protocol_family": protocol_family,
        "url": url,
        "period_start": period_start,
        "period_end": period_end,
        "period_bands": period_bands,
        "expected_record_types": expected_record_types,
        "capture_route": capture_route,
        "recommended_adapter": recommended_adapter,
        "recommended_image_policy": recommended_image_policy,
        "text_enrichment_path": text_enrichment_path,
        "rights_posture": rights_posture,
        "risk_notes": risk_notes,
        "priority": priority,
        "inclusion_status": inclusion_status,
        "notes": notes,
    }


def build_rows() -> list[dict[str, str]]:
    discovery_note = "1990-2026 exploratory source scan; internal triage only; not public authority or rights clearance."
    return [
        row("Another Graphic", "Global", "Independent web", "Transnational", "independent design archive / publication", "independent", "Static JS App / HTML", "https://anothergraphic.org/", "2010", "2026", "2000-2026", "contemporary graphic design projects; essays; interviews", "source-level discovery first; item rows only after source review", "html_jsonld_or_static_js_probe", "IMG00 discovery-only until item source terms reviewed; IMG02 if source viewer is explicit", "essay and project text extraction after source terms review", "unknown; do not store images", "independent contemporary site; image reuse cannot be inferred from visibility", "P0", notes=discovery_note),
        row("It's Nice That", "Global", "Independent web", "United Kingdom / transnational", "design media", "independent media", "WordPress REST / HTML", "https://www.itsnicethat.com/", "2007", "2026", "2000-2026", "design articles; project pages; interviews", "metadata + outbound source discovery; no image ingest", "wordpress_rest_or_html_adapter", "IMG00 discovery-only; quote/link source; no automatic thumbnail", "article text snippets and cited designer/source extraction", "copyrighted editorial media", "editorial images and contemporary works high-risk", "P1", notes=discovery_note),
        row("AIGA Eye on Design", "Global", "Independent web", "United States / transnational", "design media", "professional association media", "WordPress REST / HTML", "https://eyeondesign.aiga.org/", "2014", "2026", "2000-2026", "articles; interviews; critical essays", "text/source discovery; cite back to article", "wordpress_rest_or_html_adapter", "IMG00 unless explicit rights statement at item level", "article text and source/person extraction", "copyrighted editorial media", "text useful; images not reusable by default", "P1", notes=discovery_note),
        row("Slanted", "Global", "Independent web", "Germany / transnational", "design publication / type culture", "independent media", "HTML / WordPress-like", "https://www.slanted.de/", "2004", "2026", "2000-2026", "typography reports; regional design surveys; interviews", "source discovery and bibliography enrichment", "html_source_probe_then_manual_rules", "IMG00; source-return only unless explicit open license", "article text and issue metadata", "copyrighted editorial media", "publisher content requires conservative reuse", "P1", notes=discovery_note),
        row("The Brand Identity", "Global", "Independent web", "United Kingdom / transnational", "branding archive / media", "independent media", "Static JS App / HTML", "https://the-brandidentity.com/", "2010", "2026", "2000-2026", "branding projects; studio credits; images", "source discovery only; potential multi-image case study after permission review", "static_js_or_html_probe", "IMG00 discovery-only; no local image copy", "project text and studio/source extraction", "copyrighted contemporary branding", "useful for post-1990 branding but high image-rights risk", "P1", notes=discovery_note),
        row("BP&O", "Global", "Independent web", "United Kingdom / transnational", "branding archive / review", "independent media", "WordPress REST / HTML", "https://bpando.org/", "2011", "2026", "2000-2026", "brand identity case studies; studio credits", "source discovery and text extraction only", "wordpress_rest_or_html_adapter", "IMG00 discovery-only; item images require source permission", "project summary and outbound link extraction", "copyrighted contemporary branding", "editorial/project image rights vary", "P1", notes=discovery_note),
        row("Fonts In Use", "Global", "Typography", "Transnational", "typography database", "community database", "Static JS App / HTML", "https://fontsinuse.com/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "type use records; source links; tags", "metadata enrichment for typography relations; no image possession", "html_jsonld_adapter", "IMG00/IMG02 depending source return; no automatic reuse", "title/typeface/industry/source metadata", "mixed; source-linked user/editorial records", "images often user-submitted or source-derived", "P0", notes="Useful authority-like typography context, but not an image-rights authority."),
        row("People's Graphic Design Archive", "Global", "Community archive", "United States / transnational", "community archive", "community", "Static JS App / API-like", "https://peoplesgdarchive.org/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "community-submitted design records", "source registry and cross-reference; respect PGDA terms", "static_js_or_api_probe", "IMG00/IMG02 after record terms review; no automatic local copy", "metadata and citation enrichment", "community archive with item-level rights variation", "community submissions require careful provenance", "P0", notes="Important non-museum comparator; not a replacement source."),
        row("Design Reviewed", "Europe", "Independent archive", "United Kingdom", "private design archive / publication", "independent", "WordPress REST / HTML", "https://designreviewed.com/", "1920", "2026", "1931-1970; 1970-2000; 2000-2026", "scanned printed ephemera; articles; posts", "source discovery and metadata enrichment", "wordpress_rest_or_html_adapter", "IMG00 unless source explicitly permits; no scrape-and-republish", "post text and tags", "private archive scans; high image-rights caution", "already useful but not rights clearance", "P0", notes=discovery_note),
        row("Letterform Archive Blog", "North America", "Independent archive", "United States", "typography archive / institution", "nonprofit archive", "WordPress REST / HTML", "https://letterformarchive.org/news/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "articles; collection highlights; exhibitions", "text enrichment and source registry only", "wordpress_rest_or_html_adapter", "IMG00/IMG02 unless explicit open record rights", "article text; collection references", "institutional archive with rights variation", "images and collections need record-level review", "P1", notes=discovery_note),
        row("Are.na Design History Channels", "Global", "Platform discovery", "Transnational", "social bookmarking / research platform", "platform", "Static JS App / API", "https://www.are.na/", "2010", "2026", "2000-2026", "user-curated links and images; channels", "discovery signal only; resolve original sources before ingest", "discovery_signal_only_no_item_image_ingest", "IMG00 discovery-only; never use as rights source", "link graph and topic discovery", "platform repost context; not source authority", "high noise and repost risk", "P2", notes="Use only to find original sources, not as archive evidence."),
        row("Behance", "Global", "Platform discovery", "Transnational", "portfolio platform", "platform", "API / Static JS App", "https://www.behance.net/", "2005", "2026", "2000-2026", "portfolio projects; multi-image projects", "discovery signal only; creator/source verification required", "discovery_signal_only_no_item_image_ingest", "IMG00 discovery-only unless creator/source permission is separately reviewed", "project title/creator/date/tag signal only", "portfolio copyright retained by creators", "high noise; platform visibility is not license", "P2", notes=discovery_note),
        row("Pinterest", "Global", "Platform discovery", "Transnational", "visual bookmarking platform", "platform", "API / HTML", "https://www.pinterest.com/", "2010", "2026", "2000-2026", "reposted visual references and outbound links", "discovery signal only; original source resolution required", "discovery_signal_only_no_item_image_ingest", "IMG00 discovery-only; never use as rights source", "outbound link/source discovery", "reposted content; unreliable provenance", "high duplicate/noise risk", "P3", notes="Use sparingly for source discovery, not item evidence."),
        row("Cargo Sites", "Global", "Independent web", "Transnational", "portfolio hosting family", "platform / independent sites", "Cargo / HTML", "https://cargo.site/", "2006", "2026", "2000-2026", "independent portfolios; studio pages", "platform-family probe; individual site review required", "cargo_html_discovery_adapter", "IMG00 discovery-only unless creator terms reviewed", "project metadata where public and permitted", "portfolio copyright retained by creators", "site-specific terms vary", "P2", notes=discovery_note),
        row("Tumblr Design Archive Discovery", "Global", "Platform discovery", "Transnational", "blog platform", "platform", "API / RSS / HTML", "https://www.tumblr.com/", "2007", "2026", "2000-2026", "blog posts; reposted images; tags", "discovery signal only; original source resolution required", "discovery_signal_only_no_item_image_ingest", "IMG00 discovery-only; never treat repost as rights evidence", "tag/source link discovery", "mixed repost/original content", "high provenance risk", "P3", notes=discovery_note),
        row("JAGDA", "East Asia", "Japan", "Japan", "professional association", "professional association", "Static JS App / HTML", "https://www.jagda.or.jp/", "1978", "2026", "1970-2000; 2000-2026", "association records; events; member network", "source registry + institutional context", "html_source_probe_then_manual_rules", "IMG04 for source registry; IMG00/IMG02 for item-level records after review", "institutional description and event text", "association site; item images require review", "source-level evidence, not item image authority", "P0", notes=discovery_note),
        row("Tokyo Type Directors Club", "East Asia", "Japan", "Japan", "professional association / awards", "professional association", "Static JS App / HTML", "https://tokyotypedirectorsclub.org/", "1987", "2026", "1970-2000; 2000-2026", "awards; events; typography network", "source registry and authority context", "html_source_probe_then_manual_rules", "IMG04 source registry; item images require rights review", "source/event text extraction", "association awards site with image restrictions", "do not infer reuse from award display", "P0", notes=discovery_note),
        row("Tokyo ADC", "East Asia", "Japan", "Japan", "professional association / awards", "professional association", "Static JS App / HTML", "https://www.tokyoadc.com/", "1952", "2026", "1931-1970; 1970-2000; 2000-2026", "awards; annuals; association history", "source registry and event context", "html_source_probe_then_manual_rules", "IMG04 source registry; item images require rights review", "history/event text extraction", "association images not automatically reusable", "source-level only until item review", "P0", notes=discovery_note),
        row("Ginza Graphic Gallery", "East Asia", "Japan", "Japan", "exhibition archive", "gallery / institution", "Static JS App / HTML", "https://www.dnpfcp.jp/gallery/ggg/", "1986", "2026", "1970-2000; 2000-2026", "exhibition pages; designer names; dates", "exhibition metadata and source registry", "html_source_probe_then_manual_rules", "IMG04/IMG00; exhibition images need record-level review", "exhibition text and designer extraction", "DNP/gallery content rights vary", "important context but image-restricted", "P0", notes=discovery_note),
        row("ddd Gallery", "East Asia", "Japan", "Japan", "exhibition archive", "gallery / institution", "Static JS App / HTML", "https://www.dnpfcp.jp/gallery/ddd/", "1991", "2026", "1970-2000; 2000-2026", "exhibition pages; designer names; dates", "exhibition metadata and source registry", "html_source_probe_then_manual_rules", "IMG04/IMG00; no image copy unless source permits", "exhibition text extraction", "DNP/gallery content rights vary", "important for Osaka/Kyoto graphic design context", "P0", notes=discovery_note),
        row("DNP Graphic Design Archives", "East Asia", "Japan", "Japan", "design archive", "institutional archive", "HTML / collection pages", "https://www.dnpfcp.jp/gallery/archives/", "1910", "2026", "1931-1970; 1970-2000; 2000-2026", "graphic design collection records", "source registry; item probe only after terms review", "html_source_probe_then_manual_rules", "IMG00/IMG02 after record review; no automatic local copy", "archive description and item metadata", "institutional collection rights vary", "key Japanese source, rights-sensitive", "P0", notes=discovery_note),
        row("Seoul Design Foundation / DDP", "East Asia", "Korea", "South Korea", "design institution", "public design institution", "Static JS App / HTML", "https://www.ddp.or.kr/", "2000", "2026", "2000-2026", "exhibition/event/design program records", "source registry and event text", "static_js_or_html_probe", "IMG04/IMG00 unless record rights reviewed", "event and exhibition text extraction", "institutional/event content rights vary", "modern institutional source; not object archive by default", "P1", notes=discovery_note),
        row("Korea Design Foundation / Design DB", "East Asia", "Korea", "South Korea", "design database / institution", "public design institution", "HTML / Static JS App", "https://www.designdb.com/", "1970", "2026", "1970-2000; 2000-2026", "design articles; project records; policy context", "source registry and text discovery", "html_source_probe_then_manual_rules", "IMG00/IMG04 until rights reviewed", "article/source text extraction", "Korean public/design database terms require review", "language and script handling needed", "P1", notes=discovery_note),
        row("National Library of Korea Digital Collections", "East Asia", "Korea", "South Korea", "national library digital collection", "national institution", "OAI-PMH / HTML", "https://www.nl.go.kr/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "books; periodicals; posters; bibliographic records", "bibliographic/source metadata first", "oai_pmh_or_html_adapter", "IMG04 for bibliographic records; IMG02 if viewer exists", "bibliographic metadata and OCR where available", "national library rights vary by item", "strong source for Korea but adapter must be careful", "P1", notes=discovery_note),
        row("Taiwan Design Research Institute", "East Asia", "Taiwan", "Taiwan", "design institution", "public design institution", "Static JS App / HTML", "https://www.tdri.org.tw/", "2000", "2026", "2000-2026", "design policy; exhibitions; awards", "source registry and institutional context", "static_js_or_html_probe", "IMG04/IMG00; item image review required", "text/context extraction", "institutional contemporary content", "use as context, not image archive", "P1", notes=discovery_note),
        row("Taiwan Cultural Memory Bank", "East Asia", "Taiwan", "Taiwan", "cultural heritage database", "public cultural platform", "Static JS App / API", "https://memory.culture.tw/", "1895", "2026", "1931-1970; 1970-2000; 2000-2026", "cultural objects; posters; photographs; documents", "source metadata and rights-state probe", "static_js_or_api_probe", "IMG00/IMG02/IMG03 only by record-level rights evidence", "object metadata and source descriptions", "mixed public/rights states", "promising but needs adapter validation", "P0", notes=discovery_note),
        row("M+ Collections", "East Asia", "Hong Kong", "Hong Kong", "museum collection", "museum", "Static JS App / API-like", "https://www.mplus.org.hk/en/collection/", "1960", "2026", "1931-1970; 1970-2000; 2000-2026", "visual culture/design collection records", "metadata/source link; no image copy unless terms permit", "static_js_or_api_probe", "IMG02/IMG00 after record review; no automatic local copy", "object metadata and curatorial text", "museum image rights vary", "important source for Asian modern/contemporary design", "P0", notes=discovery_note),
        row("DesignSingapore Council", "Southeast Asia", "Singapore", "Singapore", "design institution", "public design institution", "HTML / Static JS App", "https://designsingapore.org/", "2003", "2026", "2000-2026", "awards; reports; design policy; designer profiles", "source registry and text enrichment", "html_source_probe_then_manual_rules", "IMG04/IMG00; no automatic image display", "report/profile text extraction", "government/public content but image rights vary", "useful for contemporary Singapore context", "P1", notes=discovery_note),
        row("National Library Board Singapore / BiblioAsia", "Southeast Asia", "Singapore", "Singapore", "library publication / heritage text", "national institution", "HTML / Search", "https://biblioasia.nlb.gov.sg/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "heritage essays; bibliographic context; print culture", "text enrichment and citations", "html_source_probe_then_manual_rules", "IMG04/text; images only by explicit item rights", "essay citation extraction", "article/images rights vary", "valuable text source for Singapore/Malaya design history", "P1", notes=discovery_note),
        row("Roots.sg", "Southeast Asia", "Singapore", "Singapore", "heritage portal / collection", "public cultural institution", "Static JS App / API-like", "https://www.roots.gov.sg/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "museum objects; posters; ephemera; heritage articles", "metadata and rights-state probe", "static_js_or_api_probe", "IMG02/IMG00; IMG03 only with explicit license", "object/article metadata extraction", "government heritage portal with item-level rights", "promising but record-specific terms needed", "P1", notes=discovery_note),
        row("Malaysian Design Archive", "Southeast Asia", "Malaysia", "Malaysia", "community/critical design archive", "independent archive", "HTML / Static JS App", "https://www.malaysiadesignarchive.org/", "1957", "2026", "1931-1970; 1970-2000; 2000-2026", "Malaysian graphic design history; essays; records", "source registry + text and link extraction", "html_source_probe_then_manual_rules", "IMG00/IMG02 after source review; no local image copy by default", "essay and record text extraction", "independent archive; rights sensitive", "core Southeast Asian counter-canon source", "P0", notes=discovery_note),
        row("Grafis Nusantara", "Southeast Asia", "Indonesia", "Indonesia", "graphic archive / design history", "independent archive", "Static JS App / HTML", "https://grafisnusantara.com/", "1940", "2026", "1931-1970; 1970-2000; 2000-2026", "Indonesian graphic design records; publications; images", "source registry and item metadata after rights review", "static_js_or_html_probe", "IMG00/IMG02 unless explicit rights evidence", "archive text and source links", "independent archive; image rights require care", "high-priority non-Western source", "P0", notes=discovery_note),
        row("IVAA Indonesian Visual Art Archive", "Southeast Asia", "Indonesia", "Indonesia", "visual art archive", "independent archive", "Archive / HTML", "https://ivaa-online.org/", "1940", "2026", "1931-1970; 1970-2000; 2000-2026", "visual art/design-adjacent records; documents; events", "source registry and relation discovery", "html_source_probe_then_manual_rules", "IMG00/IMG02 after record rights review", "metadata and event text", "visual art archive rights vary", "useful for design-adjacent Indonesian networks", "P1", notes=discovery_note),
        row("ASEAN Digital Library", "Southeast Asia", "ASEAN", "Southeast Asia", "regional digital library", "regional library network", "Search / IIIF possible", "https://www.aseanlibrary.org/", "1800", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "national library objects; documents; photographs; print culture", "metadata/source probe by country", "html_or_api_probe", "IMG02/IMG00; IMG03 only with item-level license", "metadata and OCR where available", "country/item rights vary", "macro-regional entry point for Southeast Asia", "P0", notes=discovery_note),
        row("VietGD", "Southeast Asia", "Vietnam", "Vietnam / diaspora", "design history platform", "independent/community", "HTML / Static JS App", "https://vietgd.com/", "1970", "2026", "1970-2000; 2000-2026", "Vietnamese graphic design history; articles; community projects", "source discovery and text extraction", "html_source_probe_then_manual_rules", "IMG00 discovery-only unless source terms reviewed", "article/project text extraction", "independent/community rights vary", "important if reachable; validate source status", "P1", notes=discovery_note),
        row("Thai Graphic Design Century", "Southeast Asia", "Thailand", "Thailand", "publication / archive project", "independent/research", "HTML / Publication", "https://thaigraphicdesignhistory.com/", "1850", "1960", "1830-1930; 1931-1970", "Thai print culture; graphic design history; bibliographic source", "source registry and citation text", "html_source_probe_then_manual_rules", "IMG04/text unless item rights reviewed", "publication metadata and citation extraction", "publication/project rights vary", "mostly historical but useful source context", "P1", notes="Useful source family despite not being post-1990 object material."),
        row("Design Center of the Philippines", "Southeast Asia", "Philippines", "Philippines", "design institution", "public design institution", "HTML / Static JS App", "https://designcenter.gov.ph/", "1973", "2026", "1970-2000; 2000-2026", "design policy; programs; awards; exhibitions", "source registry and institutional context", "html_source_probe_then_manual_rules", "IMG04/IMG00 unless item rights reviewed", "event/report text", "public institution content rights vary", "Philippines contemporary design context", "P1", notes=discovery_note),
        row("CIViC Archive", "South Asia", "India", "India", "popular visual culture archive", "independent/research archive", "HTML / Search", "https://civicarchives.org/", "1850", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "visual culture; print ephemera; commercial/popular graphics", "source registry and metadata request path", "html_source_probe_then_manual_rules", "IMG00/IMG02 after source terms review", "record metadata and text extraction", "rights/ordering model likely source-controlled", "high-priority South Asian source", "P0", notes=discovery_note),
        row("Priya Paul Collection", "South Asia", "India", "India", "popular visual culture collection", "private collection / public platform", "Google Arts / HTML", "https://artsandculture.google.com/partner/priya-paul-collection", "1880", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "calendar art; posters; advertisements; ephemera", "source link and metadata only; platform viewer", "google_arts_source_probe", "IMG02 platform viewer; no local copy unless rights explicit", "record metadata/context text", "platform/source image rights restricted", "important historical and contemporary South Asian visual culture", "P0", notes=discovery_note),
        row("Tasveer Ghar", "South Asia", "India / South Asia", "South Asia", "visual culture archive", "scholarly/community archive", "HTML / Google Arts", "https://tasveerghar.net/", "1850", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "popular visual culture; essays; image collections", "source registry and essay/text enrichment", "html_source_probe_then_manual_rules", "IMG00/IMG02; image rights must be checked per source", "essay and collection metadata", "mixed collection and platform rights", "important scholarly bridge source", "P0", notes=discovery_note),
        row("Design Dashtahjaat", "South Asia", "Pakistan", "Pakistan", "graphic design archive", "independent/community", "HTML / Static JS App", "https://designdashtahjaat.com/", "1947", "2026", "1931-1970; 1970-2000; 2000-2026", "Pakistani graphic design; Urdu typography; visual culture", "source registry and metadata/text discovery", "html_source_probe_then_manual_rules", "IMG00 discovery-only unless record rights reviewed", "text/source extraction", "independent/community rights vary", "important for underrepresented Pakistan design history", "P0", notes=discovery_note),
        row("SADAA", "South Asia", "Diaspora", "South Asian diaspora", "diaspora arts archive", "nonprofit archive", "HTML / Collection", "https://www.sadaa.org/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "artist/designer archives; oral history; documents", "source registry and design-adjacent relation discovery", "html_source_probe_then_manual_rules", "IMG00/IMG02 after item rights review", "archive description and source text", "diaspora archive rights vary", "useful relation/context source", "P1", notes=discovery_note),
        row("Arabic Design Archive", "MENA", "Arab world", "Egypt / Arab world", "graphic design archive", "independent archive", "Static JS App / HTML", "https://arabicdesignarchive.com/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "Arabic graphic design records; designers; objects", "source registry and item probe after rights review", "static_js_or_html_probe", "IMG00/IMG02; no automatic image copy", "record text and relation extraction", "independent archive; rights vary", "core Arabic design source", "P0", notes=discovery_note),
        row("Syrian Design Archive", "MENA", "Levant", "Syria / diaspora", "graphic design archive", "independent archive", "Static JS App / HTML", "https://syriandesignarchive.com/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "Syrian graphic design records; publications; images", "source registry and item metadata after rights review", "static_js_or_html_probe", "IMG00/IMG02; item rights review required", "archive text and source links", "independent archive; cultural sensitivity", "important non-Western design history source", "P0", notes=discovery_note),
        row("Palestinian Museum Digital Archive", "MENA", "Levant", "Palestine", "digital archive", "museum/archive", "Omeka / IIIF possible", "https://palarchive.org/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "posters; documents; photographs; cultural records", "metadata/source viewer; cultural sensitivity review", "omeka_or_html_probe", "IMG02/IMG00; respect source and cultural sensitivity policies", "metadata and contextual text", "cultural sensitivity + rights review needed", "high-value but requires careful protocol", "P0", notes=discovery_note),
        row("Arab Image Foundation", "MENA", "Levant", "Lebanon / Arab world", "photographic archive", "archive", "Static JS App / Collection", "https://arabimagefoundation.org/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "photographs; documents; visual culture records", "source registry and contextual relation discovery", "static_js_or_html_probe", "IMG00/IMG02 after item rights review", "metadata/context text", "photographic archive rights/sensitivity", "design-adjacent visual culture source", "P1", notes=discovery_note),
        row("SALT Research", "MENA", "Turkey", "Turkey", "research archive", "institutional archive", "Archive / Search", "https://archives.saltresearch.org/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "architecture/design/visual culture archives", "source metadata and record links", "archive_search_probe", "IMG00/IMG02 after source viewer review", "metadata and finding-aid text", "institutional archive rights vary", "important Turkey/MENA visual culture source", "P1", notes=discovery_note),
        row("ArchiveAfrica", "Africa", "Pan-African", "Ghana / Pan-African", "community visual archive", "independent/community archive", "Social / Static web", "https://www.archiveafrica.co/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "African visual culture; documents; photographs; design-adjacent material", "source registry/contact-first; metadata only", "discovery_signal_only_no_item_image_ingest", "IMG00 discovery-only until partnership/source terms", "source description and contact metadata", "community archive; consent and rights sensitivity", "high priority but collaboration-first", "P0", notes=discovery_note),
        row("African Activist Archive", "Africa", "Pan-African / diaspora", "United States / Africa", "activist archive", "university/archive project", "HTML / Search", "https://africanactivist.msu.edu/", "1950", "2026", "1931-1970; 1970-2000; 2000-2026", "posters; flyers; movement documents", "source metadata and rights-state probe", "html_source_probe_then_manual_rules", "IMG00/IMG02/IMG03 only by item rights evidence", "document metadata and source descriptions", "item rights vary", "strong graphic activism source", "P0", notes=discovery_note),
        row("SAHA South African History Archive", "Africa", "Southern Africa", "South Africa", "history archive", "nonprofit archive", "HTML / Collection", "https://www.saha.org.za/", "1950", "2026", "1931-1970; 1970-2000; 2000-2026", "anti-apartheid posters; documents; photographs", "source registry and item metadata after rights review", "html_source_probe_then_manual_rules", "IMG00/IMG02; item rights review required", "collection text and metadata", "political/cultural sensitivity and rights", "important Southern African graphic activism source", "P0", notes=discovery_note),
        row("Chimurenga Library", "Africa", "Pan-African", "South Africa / Pan-African", "publication/archive project", "independent archive", "Static JS App / HTML", "https://chimurengalibrary.co.za/", "1960", "2026", "1931-1970; 1970-2000; 2000-2026", "periodicals; cultural publishing; visual culture", "source registry and text/source discovery", "static_js_or_html_probe", "IMG00 discovery-only; rights and cultural review required", "publication metadata and source text", "independent archive/publication rights vary", "important African publishing/design context", "P1", notes=discovery_note),
        row("Africa Commons", "Africa", "Pan-African", "Africa", "aggregated cultural archive", "commercial/academic database", "Database / Search", "https://africacommons.net/", "1800", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "documents; photographs; collections", "source discovery; access/terms review", "database_source_probe", "IMG00/IMG02 after subscription/source terms review", "metadata/source descriptions where accessible", "subscription/database rights", "useful source map but not open image source", "P2", notes=discovery_note),
        row("Fundación IDA", "Latin America", "Southern Cone", "Argentina", "design archive", "independent foundation", "CollectiveAccess / HTML", "https://www.fundacionida.org/", "1920", "2026", "1931-1970; 1970-2000; 2000-2026", "Argentine design records; objects; designers", "source registry and API/platform probe", "collectiveaccess_or_html_probe", "IMG00/IMG02 after record rights review", "metadata and archive text", "foundation collection rights vary", "core Latin American design source", "P0", notes=discovery_note),
        row("Diseño Nacional", "Latin America", "Southern Cone", "Chile", "graphic archive", "independent archive", "HTML / WordPress-like", "https://www.disenonacional.cl/", "1840", "2000", "1830-1930; 1931-1970; 1970-2000", "Chilean posters; publications; advertising; symbols", "source registry and metadata/item probe", "html_or_wordpress_probe", "IMG00/IMG02/IMG03 only by item rights evidence", "record metadata and source text", "archive images may not be reusable", "core Chile source", "P0", notes="Historical but essential coverage source; include in source scan."),
        row("Gráfica Latina", "Latin America", "Latin America", "Latin America / diaspora", "poster archive", "independent/mobile archive", "HTML / Static JS App", "https://graficalatina.com/", "1960", "2026", "1931-1970; 1970-2000; 2000-2026", "Latin American and Latinx posters", "source registry and item metadata after rights review", "html_source_probe_then_manual_rules", "IMG00/IMG02; no automatic image reuse", "record/source text", "poster rights vary by artist/source", "strong regional poster source", "P1", notes=discovery_note),
        row("La Patria", "Latin America", "Southern Cone", "Uruguay", "graphic design archive", "independent archive", "Static JS App / HTML", "https://lapatria.uy/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "Uruguayan graphic design; logos; posters; print", "source registry and item metadata probe", "static_js_or_html_probe", "IMG00/IMG02 after item review", "record text and source extraction", "independent archive rights vary", "underrepresented Uruguay source", "P1", notes=discovery_note),
        row("Archivo de Ilustración Argentina", "Latin America", "Southern Cone", "Argentina", "illustration archive", "independent archive", "HTML / Static JS App", "https://www.archivodeilustracion.com.ar/", "1850", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "illustration; posters; magazine graphics; advertising", "source registry and metadata/text discovery", "static_js_or_html_probe", "IMG00/IMG02 after item rights review", "record and contextual text", "illustration/design-adjacent rights vary", "valuable for Argentine print culture", "P1", notes=discovery_note),
        row("Memoria Chilena", "Latin America", "Southern Cone", "Chile", "national library digital project", "national institution", "HTML / Search", "https://www.memoriachilena.gob.cl/", "1800", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "books; posters; documents; visual culture", "source metadata and OCR/text", "html_source_probe_then_manual_rules", "IMG02/IMG00; item rights review required", "metadata and OCR text", "national library item rights vary", "strong Chilean print/design context source", "P1", notes=discovery_note),
        row("Biblioteca Nacional Digital Brasil", "Latin America", "Brazil", "Brazil", "national library digital collection", "national institution", "Search / OAI possible", "https://bndigital.bn.gov.br/", "1800", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "periodicals; posters; print culture; photographs", "metadata/source viewer probe", "html_oai_or_search_probe", "IMG02/IMG00; IMG03 only with item license", "metadata/OCR text", "national library rights vary", "important Brazil source", "P1", notes=discovery_note),
        row("Archivo Mexicano de Diseño", "Latin America", "Mexico", "Mexico", "design archive / history project", "independent/research", "HTML / Static JS App", "https://archivomexicanodediseno.com/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "Mexican graphic design records and context", "source registry and metadata probe", "static_js_or_html_probe", "IMG00/IMG02 after item rights review", "record and essay text", "independent archive rights vary", "important Mexico source if reachable", "P1", notes=discovery_note),
        row("Graphic Front", "Eastern Europe", "Romania", "Romania", "graphic design archive", "independent archive", "Static JS App / HTML", "https://www.graphicfront.ro/", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "Romanian advertising; posters; stamps; logos", "source registry and item metadata probe", "static_js_or_html_probe", "IMG00/IMG02 after rights review", "record text and tags", "independent archive rights vary", "important non-Western/Eastern European source", "P1", notes=discovery_note),
        row("SCOMUS", "Eastern Europe", "Bulgaria", "Bulgaria", "socialist graphic design archive", "independent/research", "HTML / Static JS App", "https://scomus.com/", "1944", "1989", "1931-1970; 1970-2000", "Bulgarian socialist graphic design; posters; logos", "source registry and item metadata probe", "static_js_or_html_probe", "IMG00/IMG02 after rights review", "record and contextual text", "independent archive rights vary", "important socialist graphic design source", "P1", notes="Historical source family, useful for 1931-2000 coverage."),
        row("Trove", "Oceania", "Australia", "Australia", "national library aggregator", "national institution", "API / Search / IIIF possible", "https://trove.nla.gov.au/", "1800", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "newspapers; ephemera; posters; photographs", "metadata/search API and source viewer", "trove_api_or_html_probe", "IMG02/IMG00; item rights vary", "metadata/OCR text", "national library item rights vary", "key Oceania print/design context source", "P1", notes=discovery_note),
        row("AIATSIS Collection", "Oceania", "Australia / Indigenous", "Australia / Indigenous", "Indigenous cultural archive", "national institution", "Search / Collection", "https://aiatsis.gov.au/collection", "1900", "2026", "1931-1970; 1970-2000; 2000-2026", "Indigenous cultural records; posters; visual culture", "source registry only with cultural sensitivity review", "html_source_probe_then_manual_rules", "IMG00/IMG02 only after cultural and rights review", "metadata/context text", "Indigenous cultural protocols; rights sensitivity", "collaboration/sensitivity-first", "P1", notes=discovery_note),
        row("DigitalNZ", "Oceania", "New Zealand", "Aotearoa New Zealand", "national aggregator", "national aggregator", "API / Search", "https://digitalnz.org/", "1800", "2026", "1830-1930; 1931-1970; 1970-2000; 2000-2026", "posters; newspapers; ephemera; photographs", "metadata/API and source return", "digitalnz_api_or_html_probe", "IMG02/IMG00/IMG03 only by provider rights", "metadata and source descriptions", "provider-level rights vary", "key Aotearoa source; provider-specific review required", "P1", notes=discovery_note),
    ]


def main() -> None:
    rows = build_rows()
    for index, item in enumerate(rows, start=1):
        item["candidate_id"] = f"CSS{index:04d}"
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDNAMES)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows)} contemporary source candidates to {OUTPUT}")


if __name__ == "__main__":
    main()
